/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leuraojedamecanicos;


import ConexionBD.ConexionMySQL;
import ConexionBD.ConexionReporteNotas;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import mecanicos.SoloMayusculas;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Gerardo
 */
public class Busquedas extends javax.swing.JFrame {

    /**
     * Creates new form Busquedas
     */
    public Busquedas() {
        initComponents();
        Mostrar("");
        this.setLocationRelativeTo(null);
        EntradaPlaca.setDocument(new SoloMayusculas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BotonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        EtiquetaPrevi = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        EntradaPlaca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        BotonImprimir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        EntradaId = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Busqueda De Notas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 10, 330, 40));

        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 121, 80, 30));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 169, 990, 240));
        getContentPane().add(EtiquetaPrevi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 220, 210));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));
        getContentPane().add(EntradaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 110, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Placa:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida (1).png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 70, 70));

        BotonImprimir.setText("Imprimir Nota");
        BotonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo5.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 0, 1070, 480));
        getContentPane().add(EntradaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:
        Mostrar(EntradaPlaca.getText());
        
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu menu=new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "WARNING",JOptionPane.WARNING_MESSAGE,
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        // Instrucciones si verdadero
        System.exit(0);
        } else {
            // Instrucciones si falso

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int i=Tabla.getSelectedRow();
        TableModel model=Tabla.getModel();
        EntradaId.setText(model.getValueAt(i,0).toString());
    }//GEN-LAST:event_TablaMouseClicked

    private void BotonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonImprimirActionPerformed
        // TODO add your handling code here:
        String Id=EntradaId.getText();
        System.out.println("Se llevara este dato a la busqueda:"+Id);
        ConexionReporteNotas nota=new ConexionReporteNotas();
        try {  
            nota.JasperNota(Id);
        } catch (JRException | SQLException ex) {
            Logger.getLogger(Busquedas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonImprimirActionPerformed

    
    public void Mostrar(String Placa)
    {
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
       DefaultTableModel model=new DefaultTableModel();
        model.addColumn("Numero Notas");
        model.addColumn("Numero de Cliente");
        model.addColumn("Nombre");
        model.addColumn("Apellido Paterno");
        model.addColumn("Apellido Materno");
        model.addColumn("Numero Vehículo");
        model.addColumn("Vehiculo");
        model.addColumn("Placa");
        model.addColumn("Numero De Ingreso Del vehiculo");
        model.addColumn("Fecha de Ingreso");
        Tabla.setModel(model);
        String sql="";
        if(Placa.equals(""))
        {
           sql="Select Notas.IdNotas,Notas.NumeroCliente,Cliente.Nombre,Cliente.ApellidoP,Cliente.ApellidoM,vehiculos.IdVehiculos,vehiculos.Vehiculo,vehiculos.Placa,ingresarvehiculos.IdIngresoVehiculo,ingresarvehiculos.FechaIngreso from notas Inner Join cliente On notas.NumeroCliente=cliente.IdCliente Join vehiculos on notas.NumeroVehiculo=vehiculos.IdVehiculos join ingresarvehiculos on vehiculos.IdVehiculos=ingresarvehiculos.NumeroVehiculo;"; 
        }else{
            sql="select notas.IdNotas,notas.NumeroCliente,cliente.Nombre,cliente.ApellidoP,cliente.ApellidoM,notas.NumeroVehiculo,vehiculos.vehiculo,vehiculos.Placa,notas.NumeroIngresoVehiculo,ingresarvehiculos.FechaIngreso from notas,cliente,vehiculos,ingresarvehiculos where notas.NumeroCliente=cliente.IdCliente and notas.NumeroVehiculo=IdVehiculos and notas.NumeroIngresoVehiculo=ingresarvehiculos.IdIngresoVehiculo and vehiculos.Placa like '%"+Placa+"%';";
        }
        String Usuarios[]=new String[10];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                Usuarios[0]=con.resultado.getString(1);
                Usuarios[1]=con.resultado.getString(2);
                Usuarios[2]=con.resultado.getString(3);
                Usuarios[3]=con.resultado.getString(4);
                Usuarios[4]=con.resultado.getString(5);
                Usuarios[5]=con.resultado.getString(6);
                Usuarios[6]=con.resultado.getString(7);
                Usuarios[7]=con.resultado.getString(8);
                Usuarios[8]=con.resultado.getString(9);
                Usuarios[9]=con.resultado.getString(10);
                model.addRow(Usuarios);
            }
            Tabla.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busquedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busquedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busquedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busquedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busquedas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonImprimir;
    private javax.swing.JTextField EntradaId;
    private javax.swing.JTextField EntradaPlaca;
    private javax.swing.JLabel EtiquetaPrevi;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
