/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leuraojedamecanicos;


import ConexionBD.ConexionMySQL;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mecanicos.SoloMayusculas;

/**
 *
 * @author Gerardo
 */
public final class Diagnostico extends javax.swing.JFrame {

    /**
     * Creates new form Nota
     */
      
    public Diagnostico() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LogoH.png")));
        //trasparencia()
        EntradaBusquedaPlaca.setDocument(new SoloMayusculas());
        EntradaTCofreAb.setDocument(new SoloMayusculas());
        EntradaObservaciones.setDocument(new SoloMayusculas());
        EntradaTecnico.setDocument(new SoloMayusculas());
        
        String nt=ObtenerNumeroNota();
        int id=Integer.parseInt(nt);
        int ID=id+1;
        EtiquetaNotaN.setText(""+ID);
          this.setLocationRelativeTo(null);
         
          //Prueba();
    }
    //Metodo para hacer trasparentes cualquier boton o "componente" 
    /*public void trasparencia()
    {
        RadioBuenEstado.setOpaque(false);
        RadioBuenEstado.setContentAreaFilled(false);
        RadioBuenEstado.setBorderPainted(false);
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupEstadoCarro = new javax.swing.ButtonGroup();
        buttonGroupNeumaticos = new javax.swing.ButtonGroup();
        buttonGroupFrenosD = new javax.swing.ButtonGroup();
        buttonGroupFrenosT = new javax.swing.ButtonGroup();
        buttonGroupLimpiaP = new javax.swing.ButtonGroup();
        buttonGroupBateria = new javax.swing.ButtonGroup();
        buttonGroupAmortiguadores = new javax.swing.ButtonGroup();
        buttonGroupSuspencionD = new javax.swing.ButtonGroup();
        buttonGroupSuspencionT = new javax.swing.ButtonGroup();
        buttonGroupBalerosDeRuedasD = new javax.swing.ButtonGroup();
        buttonGroupBalerosDeRuedasT = new javax.swing.ButtonGroup();
        buttonGroupDireccion = new javax.swing.ButtonGroup();
        buttonGroupAfinacion = new javax.swing.ButtonGroup();
        buttonGroupMangueras = new javax.swing.ButtonGroup();
        buttonGroupSistemaEscape = new javax.swing.ButtonGroup();
        buttonGroupBandasYPoleas = new javax.swing.ButtonGroup();
        buttonGroupNivelesFluidos = new javax.swing.ButtonGroup();
        buttonGroupLuces = new javax.swing.ButtonGroup();
        Titulo = new javax.swing.JLabel();
        EntradaCliente = new javax.swing.JTextField();
        EntradaDireccionC = new javax.swing.JTextField();
        EntradaTEL = new javax.swing.JTextField();
        EntradaVehiculo = new javax.swing.JTextField();
        EntradaPlaca = new javax.swing.JTextField();
        EntradaSerie = new javax.swing.JTextField();
        EtiquetaFecha = new javax.swing.JLabel();
        EtiquetaPlaca = new javax.swing.JLabel();
        EtiquetaVehiculo = new javax.swing.JLabel();
        EtiquetaTEL = new javax.swing.JLabel();
        EtiquetaCliente = new javax.swing.JLabel();
        EtiquetaDireccion = new javax.swing.JLabel();
        EtiquetaTecnico = new javax.swing.JLabel();
        EtiquetaSerie = new javax.swing.JLabel();
        EtiquetaTEstado = new javax.swing.JLabel();
        EtiquetaTCofre = new javax.swing.JLabel();
        RadioBuenEstado = new javax.swing.JRadioButton();
        RadioAtencion = new javax.swing.JRadioButton();
        RadioAteInmed = new javax.swing.JRadioButton();
        EtiquetaInspe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BotonRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EntradaTCofreAb = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        EntradaObservaciones = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        BottonClientesVehiculosBusqueda = new javax.swing.JButton();
        EtiquetaNotaN = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        EntradaBusquedaPlaca = new javax.swing.JTextField();
        BusquedaRellenarPorNombre = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        EntradaId = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        EntradaApellidop = new javax.swing.JTextField();
        EntradaApellidoM = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        RadioNeumaticosB = new javax.swing.JRadioButton();
        RadioNeumaticosRA = new javax.swing.JRadioButton();
        RadioNeumaticosM = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        FondoAzulR = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        FondoAmarilloR = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        FondoRojoR = new javax.swing.JLabel();
        RadioFrenosDB = new javax.swing.JRadioButton();
        RadioFrenosDRA = new javax.swing.JRadioButton();
        RadioFrenosDM = new javax.swing.JRadioButton();
        FondoAzulRFD = new javax.swing.JLabel();
        FondoAmarilloRFD = new javax.swing.JLabel();
        FondoRojoRFD = new javax.swing.JLabel();
        RadioFrenosTB = new javax.swing.JRadioButton();
        RadioFrenosTRA = new javax.swing.JRadioButton();
        RadioFrenosTM = new javax.swing.JRadioButton();
        FondoAzulRFT = new javax.swing.JLabel();
        FondoAmarilloRFT = new javax.swing.JLabel();
        FondoRojoRFT = new javax.swing.JLabel();
        RadioLimpiaPB = new javax.swing.JRadioButton();
        RadioLimpiaPRA = new javax.swing.JRadioButton();
        RadioLimpiaPM = new javax.swing.JRadioButton();
        FondoAzulRLP = new javax.swing.JLabel();
        FondoAmarillorRLP = new javax.swing.JLabel();
        FondoRojoRLP = new javax.swing.JLabel();
        RadioBateriaB = new javax.swing.JRadioButton();
        RadioBateriaRA = new javax.swing.JRadioButton();
        RadioBateriaM = new javax.swing.JRadioButton();
        FondoAzulRB = new javax.swing.JLabel();
        FondoAmarillorRB = new javax.swing.JLabel();
        FondoRojoRB = new javax.swing.JLabel();
        RadioAmortiB = new javax.swing.JRadioButton();
        RadioAmortiRA = new javax.swing.JRadioButton();
        RadioAmortiM = new javax.swing.JRadioButton();
        FondoRojoRAt = new javax.swing.JLabel();
        FondoAmarillorRAt = new javax.swing.JLabel();
        FondoAzulRAt = new javax.swing.JLabel();
        RadioSuspencionDB = new javax.swing.JRadioButton();
        RadioSuspencionDRA = new javax.swing.JRadioButton();
        RadioSuspencionDM = new javax.swing.JRadioButton();
        FondoAzulRAt1 = new javax.swing.JLabel();
        FondoAmarillorRAt1 = new javax.swing.JLabel();
        FondoRojoRAt1 = new javax.swing.JLabel();
        RadioSuspencionTB = new javax.swing.JRadioButton();
        RadioSuspencionTRA = new javax.swing.JRadioButton();
        RadioSuspencionTM = new javax.swing.JRadioButton();
        FondoRojoRAtT = new javax.swing.JLabel();
        FondoAmarillorRAtT = new javax.swing.JLabel();
        FondoAzulRAtT = new javax.swing.JLabel();
        RadioBaleroRDB = new javax.swing.JRadioButton();
        RadioBaleroRDRA = new javax.swing.JRadioButton();
        RadioBaleroRDM = new javax.swing.JRadioButton();
        FondoRojoRBalerosD = new javax.swing.JLabel();
        FondoAmarillorRBalerosD = new javax.swing.JLabel();
        FondoAzulRBalerosD = new javax.swing.JLabel();
        RadioBaleroRTB = new javax.swing.JRadioButton();
        RadioBaleroRTRA = new javax.swing.JRadioButton();
        RadioBaleroRTM = new javax.swing.JRadioButton();
        FondoRojoRBalerosT = new javax.swing.JLabel();
        FondoAmarillorRBalerosT = new javax.swing.JLabel();
        FondoAzulRBalerosT = new javax.swing.JLabel();
        RadioDireccionB = new javax.swing.JRadioButton();
        RadioDireccionRA = new javax.swing.JRadioButton();
        RadioDireccionM = new javax.swing.JRadioButton();
        FondoRojo = new javax.swing.JLabel();
        FondoAmarillo = new javax.swing.JLabel();
        FondoAzul = new javax.swing.JLabel();
        RadioAfinacionB = new javax.swing.JRadioButton();
        RadioAfinacionRA = new javax.swing.JRadioButton();
        RadioAfinacionM = new javax.swing.JRadioButton();
        FondoRojo1 = new javax.swing.JLabel();
        FondoAmarillo1 = new javax.swing.JLabel();
        FondoAzul1 = new javax.swing.JLabel();
        RadioManguerasB = new javax.swing.JRadioButton();
        RadioManguerasRA = new javax.swing.JRadioButton();
        RadioManguerasM = new javax.swing.JRadioButton();
        FondoAzul2 = new javax.swing.JLabel();
        FondoAmarillo2 = new javax.swing.JLabel();
        FondoRojo2 = new javax.swing.JLabel();
        RadioSistemaEscapeB = new javax.swing.JRadioButton();
        RadioSistemaEscapeRA = new javax.swing.JRadioButton();
        RadioSistemaEscapeM = new javax.swing.JRadioButton();
        FondoAzul3 = new javax.swing.JLabel();
        FondoAmarillo3 = new javax.swing.JLabel();
        FondoRojo3 = new javax.swing.JLabel();
        RadioBYPB = new javax.swing.JRadioButton();
        RadioBYPRA = new javax.swing.JRadioButton();
        RadioBYPM = new javax.swing.JRadioButton();
        FondoAzul4 = new javax.swing.JLabel();
        FondoAmarillo4 = new javax.swing.JLabel();
        FondoRojo4 = new javax.swing.JLabel();
        RadioNFB = new javax.swing.JRadioButton();
        RadioNFRA = new javax.swing.JRadioButton();
        RadioNFM = new javax.swing.JRadioButton();
        FondoRojo5 = new javax.swing.JLabel();
        FondoAmarillo5 = new javax.swing.JLabel();
        FondoAzul5 = new javax.swing.JLabel();
        RadioLucesB = new javax.swing.JRadioButton();
        RadioLucesM = new javax.swing.JRadioButton();
        RadioLucesRA = new javax.swing.JRadioButton();
        EntradaTecnico = new javax.swing.JTextField();
        FondoAzul6 = new javax.swing.JLabel();
        FondoAmarillo6 = new javax.swing.JLabel();
        FondoRojo6 = new javax.swing.JLabel();
        Fecha = new com.toedter.calendar.JDateChooser();
        Fondo = new javax.swing.JLabel();
        EntradaIdVehiculo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Titulo.setForeground(java.awt.Color.white);
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Diagnóstico");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 180, 40));

        EntradaCliente.setEnabled(false);
        getContentPane().add(EntradaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 200, 30));

        EntradaDireccionC.setEnabled(false);
        getContentPane().add(EntradaDireccionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, 170, 30));

        EntradaTEL.setEnabled(false);
        EntradaTEL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaTELKeyTyped(evt);
            }
        });
        getContentPane().add(EntradaTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 170, 30));

        EntradaVehiculo.setEnabled(false);
        getContentPane().add(EntradaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, 160, 30));

        EntradaPlaca.setEnabled(false);
        getContentPane().add(EntradaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, 160, 30));

        EntradaSerie.setEnabled(false);
        getContentPane().add(EntradaSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, 160, 30));

        EtiquetaFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaFecha.setForeground(java.awt.Color.white);
        EtiquetaFecha.setText("<html> Fecha <p>del<p>Diagnostico: <html>");
        getContentPane().add(EtiquetaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 130, 70, 60));
        EtiquetaFecha.getAccessibleContext().setAccessibleName("Fecha:");

        EtiquetaPlaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaPlaca.setForeground(java.awt.Color.white);
        EtiquetaPlaca.setText("Placa:");
        getContentPane().add(EtiquetaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 80, 30));

        EtiquetaVehiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaVehiculo.setForeground(java.awt.Color.white);
        EtiquetaVehiculo.setText("Vehículo:");
        getContentPane().add(EtiquetaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 80, 30));

        EtiquetaTEL.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaTEL.setForeground(java.awt.Color.white);
        EtiquetaTEL.setText("Telefono:");
        getContentPane().add(EtiquetaTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 80, 30));

        EtiquetaCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaCliente.setForeground(java.awt.Color.white);
        EtiquetaCliente.setText("Nombre:");
        getContentPane().add(EtiquetaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 50, 20));

        EtiquetaDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaDireccion.setForeground(java.awt.Color.white);
        EtiquetaDireccion.setText("Direccion:");
        getContentPane().add(EtiquetaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 70, 30));

        EtiquetaTecnico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaTecnico.setForeground(java.awt.Color.white);
        EtiquetaTecnico.setText("Tecnico:");
        getContentPane().add(EtiquetaTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 90, 80, 30));

        EtiquetaSerie.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaSerie.setForeground(java.awt.Color.white);
        EtiquetaSerie.setText("Serie:");
        getContentPane().add(EtiquetaSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 80, 30));

        EtiquetaTEstado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaTEstado.setForeground(java.awt.Color.white);
        EtiquetaTEstado.setText("Estado del Veículo");
        getContentPane().add(EtiquetaTEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, -1, -1));

        EtiquetaTCofre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaTCofre.setForeground(java.awt.Color.white);
        EtiquetaTCofre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        EtiquetaTCofre.setText("Inspeccion a cofre abierto");
        getContentPane().add(EtiquetaTCofre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 170, -1));

        RadioBuenEstado.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupEstadoCarro.add(RadioBuenEstado);
        RadioBuenEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioBuenEstado.setText("Buenas Condiciones");
        getContentPane().add(RadioBuenEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 160, 40));

        RadioAtencion.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupEstadoCarro.add(RadioAtencion);
        RadioAtencion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioAtencion.setText("Requiere Atención");
        getContentPane().add(RadioAtencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 270, 150, 40));

        RadioAteInmed.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupEstadoCarro.add(RadioAteInmed);
        RadioAteInmed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioAteInmed.setText("Atencion Inmediata");
        getContentPane().add(RadioAteInmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 270, 160, 40));

        EtiquetaInspe.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaInspe.setForeground(java.awt.Color.white);
        EtiquetaInspe.setText("Inspeccion Puntos Basicos De seguridad:");
        getContentPane().add(EtiquetaInspe, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Observaciones y Puntos Adicionales");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, 260, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 660, 50, 10));

        BotonRegistrar.setText("Registrar");
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 670, 170, 40));

        EntradaTCofreAb.setColumns(20);
        EntradaTCofreAb.setRows(5);
        jScrollPane1.setViewportView(EntradaTCofreAb);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 690, 80));

        EntradaObservaciones.setColumns(20);
        EntradaObservaciones.setRows(5);
        jScrollPane2.setViewportView(EntradaObservaciones);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 1060, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Número De Diagnóstico:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, 160, 30));

        BottonClientesVehiculosBusqueda.setText("Clientes y Vehiculos Registrados");
        BottonClientesVehiculosBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottonClientesVehiculosBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(BottonClientesVehiculosBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        EtiquetaNotaN.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EtiquetaNotaN.setForeground(java.awt.Color.white);
        getContentPane().add(EtiquetaNotaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 50, 80, 30));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        Back.setBorder(null);
        Back.setBorderPainted(false);
        Back.setContentAreaFilled(false);
        Back.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        Back.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso (1).png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 60));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Neumaticos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 70, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("<html>Frenos <p> Delanteros:<html>");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("<html> Frenos <p> Traseros: <html>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 60, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("<html>Amorti-<p>guadores:<html>");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 60, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("<html>Suspención <p> Delantera:<html>");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 70, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("<HTML>Suspención<P>Trasera:<HTML>");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 70, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Direccion:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 60, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("<HTML>Bandas y <P>poleas <P>de acc.:<HTML>");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, 60, 60));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("Mangueras:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 70, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("<HTML> Niveles de <P>Fluidos: <HTML>");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 380, 70, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Luces:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 430, 50, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("<html> Limpia <p>Parabrisas: <html>");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("Bateria:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("<HTML>Baleros de <P>Rueda Dela:<HTML>");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 70, 40));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("<HTML>Baleros de<P> Rueda Tras. :<HTML>");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 80, 40));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setText("<HTML>Sistema <P>de Escape:<HTML>");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 70, 40));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setText("Afinacion:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 60, -1));
        getContentPane().add(EntradaBusquedaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 100, 40));

        BusquedaRellenarPorNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BusquedaRellenarPorNombre.setText("Buscar");
        BusquedaRellenarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusquedaRellenarPorNombreActionPerformed(evt);
            }
        });
        getContentPane().add(BusquedaRellenarPorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 80, 40));

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Rellenar Datos Del cliente");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 70, 250, -1));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Placa");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 50, 40));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("Id Cliente:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        EntradaId.setEnabled(false);
        getContentPane().add(EntradaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 110, 30));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setForeground(java.awt.Color.white);
        jLabel25.setText("ApellidoP:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, 20));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setForeground(java.awt.Color.white);
        jLabel26.setText("ApellidoM:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, 20));

        EntradaApellidop.setEnabled(false);
        getContentPane().add(EntradaApellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 200, 30));

        EntradaApellidoM.setEnabled(false);
        getContentPane().add(EntradaApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 200, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 70, 70));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 260, 100));

        buttonGroupNeumaticos.add(RadioNeumaticosB);
        RadioNeumaticosB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioNeumaticosB.setForeground(new java.awt.Color(255, 255, 255));
        RadioNeumaticosB.setText("Bien");
        getContentPane().add(RadioNeumaticosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 60, 20));

        buttonGroupNeumaticos.add(RadioNeumaticosRA);
        RadioNeumaticosRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioNeumaticosRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioNeumaticosRA.setText("R.Atención");
        getContentPane().add(RadioNeumaticosRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        buttonGroupNeumaticos.add(RadioNeumaticosM);
        RadioNeumaticosM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioNeumaticosM.setForeground(new java.awt.Color(255, 255, 255));
        RadioNeumaticosM.setText("Mal");
        getContentPane().add(RadioNeumaticosM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 50, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        jLabel32.setText("jLabel27");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 170, 60));

        FondoAzulR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzulR.setText("jLabel27");
        getContentPane().add(FondoAzulR, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 70, 40));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        jLabel33.setText("jLabel27");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, 170, 60));

        FondoAmarilloR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarilloR.setText("jLabel27");
        getContentPane().add(FondoAmarilloR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 100, 40));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        jLabel34.setText("jLabel27");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 260, 170, 60));

        FondoRojoR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojoR.setText("jLabel27");
        getContentPane().add(FondoRojoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 50, 40));

        buttonGroupFrenosD.add(RadioFrenosDB);
        RadioFrenosDB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioFrenosDB.setForeground(new java.awt.Color(255, 255, 255));
        RadioFrenosDB.setText("Bien");
        getContentPane().add(RadioFrenosDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 60, 20));

        buttonGroupFrenosD.add(RadioFrenosDRA);
        RadioFrenosDRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioFrenosDRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioFrenosDRA.setText("R.Atención");
        getContentPane().add(RadioFrenosDRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        buttonGroupFrenosD.add(RadioFrenosDM);
        RadioFrenosDM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioFrenosDM.setForeground(new java.awt.Color(255, 255, 255));
        RadioFrenosDM.setText("Mal");
        getContentPane().add(RadioFrenosDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 50, -1));

        FondoAzulRFD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzulRFD.setText("jLabel27");
        getContentPane().add(FondoAzulRFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 70, 40));

        FondoAmarilloRFD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarilloRFD.setText("jLabel27");
        getContentPane().add(FondoAmarilloRFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 100, 40));

        FondoRojoRFD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojoRFD.setText("jLabel27");
        getContentPane().add(FondoRojoRFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 50, 40));

        buttonGroupFrenosT.add(RadioFrenosTB);
        RadioFrenosTB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioFrenosTB.setForeground(new java.awt.Color(255, 255, 255));
        RadioFrenosTB.setText("Bien");
        getContentPane().add(RadioFrenosTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 60, 20));

        buttonGroupFrenosT.add(RadioFrenosTRA);
        RadioFrenosTRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioFrenosTRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioFrenosTRA.setText("R.Atención");
        getContentPane().add(RadioFrenosTRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, -1, -1));

        buttonGroupFrenosT.add(RadioFrenosTM);
        RadioFrenosTM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioFrenosTM.setForeground(new java.awt.Color(255, 255, 255));
        RadioFrenosTM.setText("Mal");
        getContentPane().add(RadioFrenosTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 500, 50, -1));

        FondoAzulRFT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzulRFT.setText("jLabel27");
        getContentPane().add(FondoAzulRFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 70, 40));

        FondoAmarilloRFT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarilloRFT.setText("jLabel27");
        getContentPane().add(FondoAmarilloRFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 100, 40));

        FondoRojoRFT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojoRFT.setText("jLabel27");
        getContentPane().add(FondoRojoRFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 50, 40));

        buttonGroupLimpiaP.add(RadioLimpiaPB);
        RadioLimpiaPB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioLimpiaPB.setForeground(new java.awt.Color(255, 255, 255));
        RadioLimpiaPB.setText("Bien");
        getContentPane().add(RadioLimpiaPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 60, 20));

        buttonGroupLimpiaP.add(RadioLimpiaPRA);
        RadioLimpiaPRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioLimpiaPRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioLimpiaPRA.setText("R.Atención");
        getContentPane().add(RadioLimpiaPRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, -1));

        buttonGroupLimpiaP.add(RadioLimpiaPM);
        RadioLimpiaPM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioLimpiaPM.setForeground(new java.awt.Color(255, 255, 255));
        RadioLimpiaPM.setText("Mal");
        getContentPane().add(RadioLimpiaPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 50, -1));

        FondoAzulRLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzulRLP.setText("jLabel27");
        getContentPane().add(FondoAzulRLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 70, 40));

        FondoAmarillorRLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillorRLP.setText("jLabel27");
        getContentPane().add(FondoAmarillorRLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 100, 40));

        FondoRojoRLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojoRLP.setText("jLabel27");
        getContentPane().add(FondoRojoRLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 50, 40));

        buttonGroupBateria.add(RadioBateriaB);
        RadioBateriaB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioBateriaB.setForeground(new java.awt.Color(255, 255, 255));
        RadioBateriaB.setText("Bien");
        getContentPane().add(RadioBateriaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 60, 20));

        buttonGroupBateria.add(RadioBateriaRA);
        RadioBateriaRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioBateriaRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioBateriaRA.setText("R.Atención");
        getContentPane().add(RadioBateriaRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 600, -1, -1));

        buttonGroupBateria.add(RadioBateriaM);
        RadioBateriaM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioBateriaM.setForeground(new java.awt.Color(255, 255, 255));
        RadioBateriaM.setText("Mal");
        getContentPane().add(RadioBateriaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 50, -1));

        FondoAzulRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzulRB.setText("jLabel27");
        getContentPane().add(FondoAzulRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 70, 40));

        FondoAmarillorRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillorRB.setText("jLabel27");
        getContentPane().add(FondoAmarillorRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 100, 40));

        FondoRojoRB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojoRB.setText("jLabel27");
        getContentPane().add(FondoRojoRB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 50, 40));

        buttonGroupAmortiguadores.add(RadioAmortiB);
        RadioAmortiB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioAmortiB.setForeground(new java.awt.Color(255, 255, 255));
        RadioAmortiB.setText("Bien");
        getContentPane().add(RadioAmortiB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 60, 20));

        buttonGroupAmortiguadores.add(RadioAmortiRA);
        RadioAmortiRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioAmortiRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioAmortiRA.setText("R.Atención");
        getContentPane().add(RadioAmortiRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        buttonGroupAmortiguadores.add(RadioAmortiM);
        RadioAmortiM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioAmortiM.setForeground(new java.awt.Color(255, 255, 255));
        RadioAmortiM.setText("Mal");
        getContentPane().add(RadioAmortiM, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 50, -1));

        FondoRojoRAt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojoRAt.setText("jLabel27");
        getContentPane().add(FondoRojoRAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 50, 40));

        FondoAmarillorRAt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillorRAt.setText("jLabel27");
        getContentPane().add(FondoAmarillorRAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 100, 40));

        FondoAzulRAt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzulRAt.setText("jLabel27");
        getContentPane().add(FondoAzulRAt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 70, 40));

        buttonGroupSuspencionD.add(RadioSuspencionDB);
        RadioSuspencionDB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioSuspencionDB.setForeground(new java.awt.Color(255, 255, 255));
        RadioSuspencionDB.setText("Bien");
        getContentPane().add(RadioSuspencionDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 60, 20));

        buttonGroupSuspencionD.add(RadioSuspencionDRA);
        RadioSuspencionDRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioSuspencionDRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioSuspencionDRA.setText("R.Atención");
        getContentPane().add(RadioSuspencionDRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        buttonGroupSuspencionD.add(RadioSuspencionDM);
        RadioSuspencionDM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioSuspencionDM.setForeground(new java.awt.Color(255, 255, 255));
        RadioSuspencionDM.setText("Mal");
        getContentPane().add(RadioSuspencionDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 50, -1));

        FondoAzulRAt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzulRAt1.setText("jLabel27");
        getContentPane().add(FondoAzulRAt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 70, 40));

        FondoAmarillorRAt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillorRAt1.setText("jLabel27");
        getContentPane().add(FondoAmarillorRAt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 100, 40));

        FondoRojoRAt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojoRAt1.setText("jLabel27");
        getContentPane().add(FondoRojoRAt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 50, 40));

        buttonGroupSuspencionT.add(RadioSuspencionTB);
        RadioSuspencionTB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioSuspencionTB.setForeground(new java.awt.Color(255, 255, 255));
        RadioSuspencionTB.setText("Bien");
        getContentPane().add(RadioSuspencionTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 60, 20));

        buttonGroupSuspencionT.add(RadioSuspencionTRA);
        RadioSuspencionTRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioSuspencionTRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioSuspencionTRA.setText("R.Atención");
        getContentPane().add(RadioSuspencionTRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, -1, -1));

        buttonGroupSuspencionT.add(RadioSuspencionTM);
        RadioSuspencionTM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioSuspencionTM.setForeground(new java.awt.Color(255, 255, 255));
        RadioSuspencionTM.setText("Mal");
        getContentPane().add(RadioSuspencionTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 50, -1));

        FondoRojoRAtT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojoRAtT.setText("jLabel27");
        getContentPane().add(FondoRojoRAtT, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 50, 40));

        FondoAmarillorRAtT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillorRAtT.setText("jLabel27");
        getContentPane().add(FondoAmarillorRAtT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 100, 40));

        FondoAzulRAtT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzulRAtT.setText("jLabel27");
        getContentPane().add(FondoAzulRAtT, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 70, 40));

        buttonGroupBalerosDeRuedasD.add(RadioBaleroRDB);
        RadioBaleroRDB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioBaleroRDB.setForeground(new java.awt.Color(255, 255, 255));
        RadioBaleroRDB.setText("Bien");
        getContentPane().add(RadioBaleroRDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 60, 20));

        buttonGroupBalerosDeRuedasD.add(RadioBaleroRDRA);
        RadioBaleroRDRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioBaleroRDRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioBaleroRDRA.setText("R.Atención");
        getContentPane().add(RadioBaleroRDRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, -1, -1));

        buttonGroupBalerosDeRuedasD.add(RadioBaleroRDM);
        RadioBaleroRDM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioBaleroRDM.setForeground(new java.awt.Color(255, 255, 255));
        RadioBaleroRDM.setText("Mal");
        getContentPane().add(RadioBaleroRDM, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 550, 50, -1));

        FondoRojoRBalerosD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojoRBalerosD.setText("jLabel27");
        getContentPane().add(FondoRojoRBalerosD, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 50, 40));

        FondoAmarillorRBalerosD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillorRBalerosD.setText("jLabel27");
        getContentPane().add(FondoAmarillorRBalerosD, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 100, 40));

        FondoAzulRBalerosD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzulRBalerosD.setText("jLabel27");
        getContentPane().add(FondoAzulRBalerosD, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 540, 70, 40));

        buttonGroupBalerosDeRuedasT.add(RadioBaleroRTB);
        RadioBaleroRTB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioBaleroRTB.setForeground(new java.awt.Color(255, 255, 255));
        RadioBaleroRTB.setText("Bien");
        getContentPane().add(RadioBaleroRTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 600, 60, 20));

        buttonGroupBalerosDeRuedasT.add(RadioBaleroRTRA);
        RadioBaleroRTRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioBaleroRTRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioBaleroRTRA.setText("R.Atención");
        getContentPane().add(RadioBaleroRTRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 600, -1, -1));

        buttonGroupBalerosDeRuedasT.add(RadioBaleroRTM);
        RadioBaleroRTM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioBaleroRTM.setForeground(new java.awt.Color(255, 255, 255));
        RadioBaleroRTM.setText("Mal");
        getContentPane().add(RadioBaleroRTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, 50, -1));

        FondoRojoRBalerosT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojoRBalerosT.setText("jLabel27");
        getContentPane().add(FondoRojoRBalerosT, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 50, 40));

        FondoAmarillorRBalerosT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillorRBalerosT.setText("jLabel27");
        getContentPane().add(FondoAmarillorRBalerosT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 100, 40));

        FondoAzulRBalerosT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzulRBalerosT.setText("jLabel27");
        getContentPane().add(FondoAzulRBalerosT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 70, 40));

        buttonGroupDireccion.add(RadioDireccionB);
        RadioDireccionB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioDireccionB.setForeground(new java.awt.Color(255, 255, 255));
        RadioDireccionB.setText("Bien");
        getContentPane().add(RadioDireccionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 60, 20));

        buttonGroupDireccion.add(RadioDireccionRA);
        RadioDireccionRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioDireccionRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioDireccionRA.setText("R.Atención");
        getContentPane().add(RadioDireccionRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, -1, -1));

        buttonGroupDireccion.add(RadioDireccionM);
        RadioDireccionM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioDireccionM.setForeground(new java.awt.Color(255, 255, 255));
        RadioDireccionM.setText("Mal");
        getContentPane().add(RadioDireccionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 50, -1));

        FondoRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojo.setText("jLabel27");
        getContentPane().add(FondoRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, 50, 40));

        FondoAmarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillo.setText("jLabel27");
        getContentPane().add(FondoAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 100, 40));

        FondoAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzul.setText("jLabel27");
        getContentPane().add(FondoAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 70, 40));

        buttonGroupAfinacion.add(RadioAfinacionB);
        RadioAfinacionB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioAfinacionB.setForeground(new java.awt.Color(255, 255, 255));
        RadioAfinacionB.setText("Bien");
        getContentPane().add(RadioAfinacionB, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, 60, 20));

        buttonGroupAfinacion.add(RadioAfinacionRA);
        RadioAfinacionRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioAfinacionRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioAfinacionRA.setText("R.Atención");
        getContentPane().add(RadioAfinacionRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, -1, -1));

        buttonGroupAfinacion.add(RadioAfinacionM);
        RadioAfinacionM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioAfinacionM.setForeground(new java.awt.Color(255, 255, 255));
        RadioAfinacionM.setText("Mal");
        getContentPane().add(RadioAfinacionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 440, 50, -1));

        FondoRojo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojo1.setText("jLabel27");
        getContentPane().add(FondoRojo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 430, 50, 40));

        FondoAmarillo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillo1.setText("jLabel27");
        getContentPane().add(FondoAmarillo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 100, 40));

        FondoAzul1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzul1.setText("jLabel27");
        getContentPane().add(FondoAzul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 70, 40));

        buttonGroupMangueras.add(RadioManguerasB);
        RadioManguerasB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioManguerasB.setForeground(new java.awt.Color(255, 255, 255));
        RadioManguerasB.setText("Bien");
        getContentPane().add(RadioManguerasB, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 60, 20));

        buttonGroupMangueras.add(RadioManguerasRA);
        RadioManguerasRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioManguerasRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioManguerasRA.setText("R.Atención");
        getContentPane().add(RadioManguerasRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, -1, -1));

        buttonGroupMangueras.add(RadioManguerasM);
        RadioManguerasM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioManguerasM.setForeground(new java.awt.Color(255, 255, 255));
        RadioManguerasM.setText("Mal");
        getContentPane().add(RadioManguerasM, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 490, 50, -1));

        FondoAzul2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzul2.setText("jLabel27");
        getContentPane().add(FondoAzul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 70, 40));

        FondoAmarillo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillo2.setText("jLabel27");
        getContentPane().add(FondoAmarillo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 100, 40));

        FondoRojo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojo2.setText("jLabel27");
        getContentPane().add(FondoRojo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 480, 50, 40));

        buttonGroupSistemaEscape.add(RadioSistemaEscapeB);
        RadioSistemaEscapeB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioSistemaEscapeB.setForeground(new java.awt.Color(255, 255, 255));
        RadioSistemaEscapeB.setText("Bien");
        getContentPane().add(RadioSistemaEscapeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 60, 20));

        buttonGroupSistemaEscape.add(RadioSistemaEscapeRA);
        RadioSistemaEscapeRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioSistemaEscapeRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioSistemaEscapeRA.setText("R.Atención");
        getContentPane().add(RadioSistemaEscapeRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, -1, -1));

        buttonGroupSistemaEscape.add(RadioSistemaEscapeM);
        RadioSistemaEscapeM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioSistemaEscapeM.setForeground(new java.awt.Color(255, 255, 255));
        RadioSistemaEscapeM.setText("Mal");
        getContentPane().add(RadioSistemaEscapeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 50, -1));

        FondoAzul3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzul3.setText("jLabel27");
        getContentPane().add(FondoAzul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 530, 70, 40));

        FondoAmarillo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillo3.setText("jLabel27");
        getContentPane().add(FondoAmarillo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 100, 40));

        FondoRojo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojo3.setText("jLabel27");
        getContentPane().add(FondoRojo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 530, 50, 40));

        buttonGroupBandasYPoleas.add(RadioBYPB);
        RadioBYPB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioBYPB.setForeground(new java.awt.Color(255, 255, 255));
        RadioBYPB.setText("Bien");
        getContentPane().add(RadioBYPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 600, 60, 20));

        buttonGroupBandasYPoleas.add(RadioBYPRA);
        RadioBYPRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioBYPRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioBYPRA.setText("R.Atención");
        getContentPane().add(RadioBYPRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 600, -1, -1));

        buttonGroupBandasYPoleas.add(RadioBYPM);
        RadioBYPM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioBYPM.setForeground(new java.awt.Color(255, 255, 255));
        RadioBYPM.setText("Mal");
        getContentPane().add(RadioBYPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 600, 50, -1));

        FondoAzul4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzul4.setText("jLabel27");
        getContentPane().add(FondoAzul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 590, 70, 40));

        FondoAmarillo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillo4.setText("jLabel27");
        getContentPane().add(FondoAmarillo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 590, 100, 40));

        FondoRojo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojo4.setText("jLabel27");
        getContentPane().add(FondoRojo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 590, 50, 40));

        buttonGroupNivelesFluidos.add(RadioNFB);
        RadioNFB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioNFB.setForeground(new java.awt.Color(255, 255, 255));
        RadioNFB.setText("Bien");
        getContentPane().add(RadioNFB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 380, 60, 20));

        buttonGroupNivelesFluidos.add(RadioNFRA);
        RadioNFRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioNFRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioNFRA.setText("R.Atención");
        getContentPane().add(RadioNFRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 380, -1, -1));

        buttonGroupNivelesFluidos.add(RadioNFM);
        RadioNFM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioNFM.setForeground(new java.awt.Color(255, 255, 255));
        RadioNFM.setText("Mal");
        getContentPane().add(RadioNFM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 380, 50, -1));

        FondoRojo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojo5.setText("jLabel27");
        getContentPane().add(FondoRojo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 370, 50, 40));

        FondoAmarillo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillo5.setText("jLabel27");
        getContentPane().add(FondoAmarillo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 370, 100, 40));

        FondoAzul5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzul5.setText("jLabel27");
        getContentPane().add(FondoAzul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 370, 70, 40));

        buttonGroupLuces.add(RadioLucesB);
        RadioLucesB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RadioLucesB.setForeground(new java.awt.Color(255, 255, 255));
        RadioLucesB.setText("Bien");
        getContentPane().add(RadioLucesB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 430, 60, 20));

        buttonGroupLuces.add(RadioLucesM);
        RadioLucesM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioLucesM.setForeground(new java.awt.Color(255, 255, 255));
        RadioLucesM.setText("Mal");
        getContentPane().add(RadioLucesM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 430, 50, -1));

        buttonGroupLuces.add(RadioLucesRA);
        RadioLucesRA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioLucesRA.setForeground(new java.awt.Color(255, 255, 255));
        RadioLucesRA.setText("R.Atención");
        getContentPane().add(RadioLucesRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 430, -1, -1));

        EntradaTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaTecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(EntradaTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 150, 30));

        FondoAzul6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        FondoAzul6.setText("jLabel27");
        getContentPane().add(FondoAzul6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 420, 70, 40));

        FondoAmarillo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        FondoAmarillo6.setText("jLabel27");
        getContentPane().add(FondoAmarillo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 420, 100, 40));

        FondoRojo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        FondoRojo6.setText("jLabel27");
        getContentPane().add(FondoRojo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 420, 50, 40));
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 160, 140, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo5.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 730));
        getContentPane().add(EntradaIdVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        // TODO add your handling code here:
        if(EntradaTecnico.getText().isEmpty()||Fecha.getDate() == null){
            JOptionPane.showMessageDialog(null, "Por favor chequea el campo faltante", "ERROR", 0);

        }else{
        //convercion de datos
        int idCliente=Integer.parseInt(EntradaId.getText());
        int idVehiculo=Integer.parseInt(EntradaIdVehiculo.getText());
        //int KM=Integer.parseInt(EntradaKm.getText());
        //Obtencion de valores 
        String Neumaticos=ObtenerDatosCheckNeumaticos();
        String FrenosD=ObtenerDatosCheckFrenosD();
        String FrenosT=ObtenerDatosCheckFrenosT();
        String LimpiaP=ObtenerDatosCheckLimpiaP();
        String Bateria=ObtenerDatosCheckBateria();
        String Amorti=ObtenerDatosCheckAmortiguadores();
        String SuspencionD=ObtenerDatosCheckSuspencionD();
        String SuspencionT=ObtenerDatosCheckSuspencionT();
        String BaleroD=ObtenerDatosCheckBalerosD();
        String BaleroT=ObtenerDatosCheckBalerosT();
        String Direccion=ObtenerDatosChecksDireccion();
        String BandasyP=ObtenerDatosChecksBandasYPo();
        String Mangueras=ObtenerDatosChecksMangueras();
        String NivelFl=ObtenerDatosChecksNivelesDeFlu();
        String Luces=ObtenerDatosChecksLuces();
        String SistemaEsca=ObtenerDatosChecksSistemaDeEscape();
        String Afinacion=ObtenerDatosChecksAfinacion();
        //Tanque
        //String Tanque= String.valueOf(SlGasolina.getValue());
        //Estado o atencion del vehiculo
        String Estado;
        Estado=EstadoCarro();
        /////modificaion de fecha para poder guardarla en mysql
        java.util.Date DateI = Fecha.getDate();
        long di=DateI.getTime();
        java.sql.Date fecha = new java.sql.Date(di);
        ///////Pedir el numero siguiente d ela nota
        String nt=ObtenerNumeroNota();
        int id=Integer.parseInt(nt);
        int ID=id+1;
        /////////PEDIR NUEMRO DEL VEHICULOS
        String ndv=EntradaIdVehiculo.getText();
        int  idv=Integer.parseInt(ndv);
        ///////////////ID ESTCDO CARRO
        String ntec=ObtenerNumeroIdEstadoCarro();
        int idec=Integer.parseInt(ntec);
        int IDEC=idec+1;
        ////// Instancia y conexion con la bd
        ConexionMySQL Con=new ConexionMySQL();
        Con.ConectarBasedeDatos();
         //METODOS PARA GUARDAR Todos Los valores
        Con.ConectarBasedeDatos();
        Con.GuardarDiagnostico(idCliente,idv,IDEC,EntradaTCofreAb.getText(),Estado,Neumaticos,FrenosD,FrenosT,Amorti,SuspencionD,SuspencionT,Direccion,BandasyP,Mangueras,NivelFl,Luces,LimpiaP,Bateria,BaleroD,BaleroT,SistemaEsca,Afinacion,EntradaObservaciones.getText(),EntradaTecnico.getText(),fecha);
        System.out.println("Todo Bien con la insercion del diagnostico");
        System.out.println(Estado);
        this.setVisible(false);
        EstadoCarro sp=new EstadoCarro(ID);
        sp.setVisible(true);
        }
    }//GEN-LAST:event_BotonRegistrarActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu menu=new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void BusquedaRellenarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusquedaRellenarPorNombreActionPerformed
        // TODO add your handling code here:
        try{
            ConexionMySQL Con=new ConexionMySQL();
            String u= EntradaBusquedaPlaca.getText();
            Con.ConectarBasedeDatos();
            String SQL="SELECT COUNT(IdVehiculos) AS i FROM vehiculos WHERE Placa='"+u+"'";
            Con.resultado=Con.sentencia.executeQuery(SQL);
            while (Con.resultado.next()){
                if (Con.resultado.getString("i").equals("1")){
                String sql="select vehiculos.IdVehiculos,cliente.IdCliente,cliente.Nombre,cliente.ApellidoP,cliente.ApellidoM, cliente.Direccion, cliente.Telefono,vehiculos.vehiculo,vehiculos.Serie,vehiculos.Placa from cliente,vehiculos where cliente.IdCliente=vehiculos.IdClienteV and vehiculos.Placa like '%"+EntradaBusquedaPlaca.getText()+"%';";
                String Usuarios[]=new String[10];
                Statement set;
                 try {
                   set=Con.conexion.createStatement();
            Con.resultado=set.executeQuery(sql);
            while(Con.resultado.next())
            {
                //Se guarda en el arreglo y del otro lado es la columna del valor
                Usuarios[0]=Con.resultado.getString(1);
                Usuarios[1]=Con.resultado.getString(2);
                Usuarios[2]=Con.resultado.getString(3);
                Usuarios[3]=Con.resultado.getString(4);
                Usuarios[4]=Con.resultado.getString(5);
                Usuarios[5]=Con.resultado.getString(6);
                Usuarios[6]=Con.resultado.getString(7);
                Usuarios[7]=Con.resultado.getString(8);
                Usuarios[8]=Con.resultado.getString(9);
                Usuarios[9]=Con.resultado.getString(10);
            }
            EntradaIdVehiculo.setText(Usuarios [0]);
            EntradaId.setText(Usuarios[1]);
            EntradaCliente.setText(Usuarios[2]);
            EntradaApellidop.setText(Usuarios[3]);
            EntradaApellidoM.setText(Usuarios[4]);
            EntradaDireccionC.setText(Usuarios[5]);
            EntradaTEL.setText(Usuarios[6]);
            EntradaVehiculo.setText(Usuarios[7]);
            EntradaSerie.setText(Usuarios[8]);
            EntradaPlaca.setText(Usuarios[9]);
            
        } catch (SQLException ex) {
            Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
  
                }else{
                    JOptionPane.showMessageDialog(null, "La placa no coincide con alguna de la base de datos.", "NO EXISTE", 0);
                    EntradaBusquedaPlaca.setText("");

                }
            }
            Con.DesconectarBasedeDatos();
        } catch (SQLException ex){
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_BusquedaRellenarPorNombreActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "WARNING",JOptionPane.WARNING_MESSAGE,
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        // Instrucciones si verdadero
        System.exit(0);
        } else {
            // Instrucciones si falso

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EntradaTELKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaTELKeyTyped
        // TODO add your handling code here:
     if(EntradaTEL.getText().length()>=10){
        evt.consume();
        getToolkit().beep();
    }else{
        char car = evt.getKeyChar();
    if(Character.isDigit(car)){
    }else{
    evt.consume();
    }
    }
    }//GEN-LAST:event_EntradaTELKeyTyped

    private void EntradaTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaTecnicoActionPerformed

    private void BottonClientesVehiculosBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottonClientesVehiculosBusquedaActionPerformed
        // TODO add your handling code here:
        ConsultaVehiculosYClientes BusCV =new ConsultaVehiculosYClientes();
        BusCV.setVisible(true);
    }//GEN-LAST:event_BottonClientesVehiculosBusquedaActionPerformed
////Metodo para obtener valor de Los botones de radio "Estado Del vehiculo
    public String EstadoCarro()
    {
        String Estado2 = null;
        if(RadioBuenEstado.isSelected())
        {
            Estado2="Buenas condiciones";
        }//else{JOptionPane.showMessageDialog(null,"Falta de seleccion de valores");}
        if(RadioAtencion.isSelected())
        {
           Estado2="Requiere atencion"; 
        }
        if(RadioAteInmed.isSelected())
        {
           Estado2="Atencion Inmediata"; 
        }
        if(Estado2==null)
        {
           
           JOptionPane.showMessageDialog(null,"Rquieres selccionar un campo en Estado del vehiculo");
        }
        return Estado2;
    }
    //Chalanes de codigo
    public int Op()
    {
        String nt=ObtenerNumeroNota();
        int id=Integer.parseInt(nt);
        int ID=id+1;
        return ID;
    }
    
    
    //Obtener valores de estado de los ckecks de cada componente :c
    public String ObtenerDatosCheckNeumaticos()
    {
        String EstadoN=null;
        if(RadioNeumaticosB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioNeumaticosRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioNeumaticosM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Neumaticos");
            }
        return EstadoN;
    }
    
    public String ObtenerDatosCheckFrenosD()
    {
        String EstadoN=null;
        if(RadioFrenosDB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioFrenosDRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioFrenosDM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Frenos Delanteros");
            }
        return EstadoN;
    }
    
    public String ObtenerDatosCheckFrenosT()
    {
        String EstadoN=null;
        if(RadioFrenosTB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioFrenosTRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioFrenosTM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Frenos Traseros");
            }
        return EstadoN;
    }
    
    public String ObtenerDatosCheckLimpiaP()
    {
        String EstadoN=null;
        if(RadioLimpiaPB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioLimpiaPRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioLimpiaPM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Limpia Parabrisas");
            }
        return EstadoN;
    }
    
    public String ObtenerDatosCheckBateria()
    {
        String EstadoN=null;
        if(RadioBateriaB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioBateriaRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioBateriaM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Bateria");
            }
        return EstadoN;
    }
    
    public String ObtenerDatosCheckAmortiguadores()
    {
        String EstadoN=null;
        if(RadioAmortiB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioAmortiRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioAmortiM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Amortiguadores");
            }
        return EstadoN;
    }
     public String ObtenerDatosCheckSuspencionD()
    {
        String EstadoN=null;
        if(RadioSuspencionDB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioSuspencionDRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioSuspencionDM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Suspencion delantera");
            }
        return EstadoN;
    }
     
      public String ObtenerDatosCheckSuspencionT()
    {
        String EstadoN=null;
        if(RadioSuspencionTB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioSuspencionTRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioSuspencionTM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Suspencion trasera");
            }
        return EstadoN;
    }
      
      public String ObtenerDatosCheckBalerosD()
    {
        String EstadoN=null;
        if(RadioBaleroRDB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioBaleroRDRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioBaleroRDM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Baleros Delanteros");
            }
        return EstadoN;
    }
     
       public String ObtenerDatosCheckBalerosT()
    {
        String EstadoN=null;
        if(RadioBaleroRTB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioBaleroRTRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioBaleroRTM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Baleros Traseros");
            }
        return EstadoN;
    }
       public String ObtenerDatosChecksDireccion()
    {
        String EstadoN=null;
        if(RadioDireccionB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioDireccionRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioDireccionM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Direccion");
            }
        return EstadoN;
    }
       public String ObtenerDatosChecksAfinacion()
    {
        String EstadoN=null;
        if(RadioAfinacionB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioAfinacionRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioAfinacionM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Afinacion");
            }
        return EstadoN;
    }
       public String ObtenerDatosChecksMangueras()
    {
        String EstadoN=null;
        if(RadioManguerasB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioManguerasRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioManguerasM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Mangueras");
            }
        return EstadoN;
    }
       public String ObtenerDatosChecksSistemaDeEscape()
    {
        String EstadoN=null;
        if(RadioSistemaEscapeB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioSistemaEscapeRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioSistemaEscapeM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado En Sistema De escape");
            }
        return EstadoN;
    }
      
       public String ObtenerDatosChecksBandasYPo()
    {
        String EstadoN=null;
        if(RadioBYPB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioBYPRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioBYPM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado en Bandas y poleas de accion");
            }
        return EstadoN;
    }
       
       public String ObtenerDatosChecksNivelesDeFlu()
    {
        String EstadoN=null;
        if(RadioNFB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioNFRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioNFM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado en Niveles de fluido");
            }
        return EstadoN;
    }
       
       public String ObtenerDatosChecksLuces()
    {
        String EstadoN=null;
        if(RadioLucesB.isSelected())
            {
            EstadoN="BIEN";
            }
        if(RadioLucesRA.isSelected())
            {
            EstadoN="Requiere Atencion";
            }
        if(RadioLucesM.isSelected())
            {
            EstadoN="Malo";
            }
        if(EstadoN==null)
            {
           JOptionPane.showMessageDialog(null,"Rquiere selccionar un campo en Estado en Luces");
            }
        return EstadoN;
    }
       /////////////////////////////////////////////
    public String Mostrar(String Nombre)
    {
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        int i=0;
        String sql="";
        if(Nombre.equals(""))
        {
           sql="SELECT * FROM cliente"; 
        }else{
            sql="SELECT * from cliente Where Nombre like'%"+Nombre+"%'";
        }
        String Usuarios[]=new String[3];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                Usuarios[0]=con.resultado.getString(2);
                Usuarios[1]=con.resultado.getString(5);
                Usuarios[2]=con.resultado.getString(6);
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
        return Usuarios[i];
    }
    
    
    public String ObtenerNumeroNota()
    {
        String id = null;
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        PreparedStatement ps;
        try {
            ps=con.conexion.prepareStatement("select IdDiagnostico from diagnostico order by IdDiagnostico desc");
            con.resultado=ps.executeQuery();
            if(con.resultado.next())
            {
            id=con.resultado.getString("IdDiagnostico");
            System.out.println(id);
            }else
            {
                id="0";
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }

    
    public String ObtenerNumeroIdEstadoCarro()
    {
        String idv = null;
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        PreparedStatement ps;
        try {
            ps=con.conexion.prepareStatement("select IdEstado from ESTADOCARRO order by IdEstado desc;");
            con.resultado=ps.executeQuery();
            if(con.resultado.next())
            {
            idv=con.resultado.getString("IdEstado");
            System.out.println("Numero del id de EstadoCarro: "+idv);
            }else
            {
                idv="0";
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        }
        return idv;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                
                new Diagnostico().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JButton BottonClientesVehiculosBusqueda;
    private javax.swing.JButton BusquedaRellenarPorNombre;
    private javax.swing.JTextField EntradaApellidoM;
    private javax.swing.JTextField EntradaApellidop;
    private javax.swing.JTextField EntradaBusquedaPlaca;
    private javax.swing.JTextField EntradaCliente;
    private javax.swing.JTextField EntradaDireccionC;
    private javax.swing.JTextField EntradaId;
    private javax.swing.JTextField EntradaIdVehiculo;
    private javax.swing.JTextArea EntradaObservaciones;
    private javax.swing.JTextField EntradaPlaca;
    private javax.swing.JTextField EntradaSerie;
    private javax.swing.JTextArea EntradaTCofreAb;
    private javax.swing.JTextField EntradaTEL;
    private javax.swing.JTextField EntradaTecnico;
    private javax.swing.JTextField EntradaVehiculo;
    private javax.swing.JLabel EtiquetaCliente;
    private javax.swing.JLabel EtiquetaDireccion;
    private javax.swing.JLabel EtiquetaFecha;
    private javax.swing.JLabel EtiquetaInspe;
    private javax.swing.JLabel EtiquetaNotaN;
    private javax.swing.JLabel EtiquetaPlaca;
    private javax.swing.JLabel EtiquetaSerie;
    private javax.swing.JLabel EtiquetaTCofre;
    private javax.swing.JLabel EtiquetaTEL;
    private javax.swing.JLabel EtiquetaTEstado;
    private javax.swing.JLabel EtiquetaTecnico;
    private javax.swing.JLabel EtiquetaVehiculo;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel FondoAmarillo;
    private javax.swing.JLabel FondoAmarillo1;
    private javax.swing.JLabel FondoAmarillo2;
    private javax.swing.JLabel FondoAmarillo3;
    private javax.swing.JLabel FondoAmarillo4;
    private javax.swing.JLabel FondoAmarillo5;
    private javax.swing.JLabel FondoAmarillo6;
    private javax.swing.JLabel FondoAmarilloR;
    private javax.swing.JLabel FondoAmarilloRFD;
    private javax.swing.JLabel FondoAmarilloRFT;
    private javax.swing.JLabel FondoAmarillorRAt;
    private javax.swing.JLabel FondoAmarillorRAt1;
    private javax.swing.JLabel FondoAmarillorRAtT;
    private javax.swing.JLabel FondoAmarillorRB;
    private javax.swing.JLabel FondoAmarillorRBalerosD;
    private javax.swing.JLabel FondoAmarillorRBalerosT;
    private javax.swing.JLabel FondoAmarillorRLP;
    private javax.swing.JLabel FondoAzul;
    private javax.swing.JLabel FondoAzul1;
    private javax.swing.JLabel FondoAzul2;
    private javax.swing.JLabel FondoAzul3;
    private javax.swing.JLabel FondoAzul4;
    private javax.swing.JLabel FondoAzul5;
    private javax.swing.JLabel FondoAzul6;
    private javax.swing.JLabel FondoAzulR;
    private javax.swing.JLabel FondoAzulRAt;
    private javax.swing.JLabel FondoAzulRAt1;
    private javax.swing.JLabel FondoAzulRAtT;
    private javax.swing.JLabel FondoAzulRB;
    private javax.swing.JLabel FondoAzulRBalerosD;
    private javax.swing.JLabel FondoAzulRBalerosT;
    private javax.swing.JLabel FondoAzulRFD;
    private javax.swing.JLabel FondoAzulRFT;
    private javax.swing.JLabel FondoAzulRLP;
    private javax.swing.JLabel FondoRojo;
    private javax.swing.JLabel FondoRojo1;
    private javax.swing.JLabel FondoRojo2;
    private javax.swing.JLabel FondoRojo3;
    private javax.swing.JLabel FondoRojo4;
    private javax.swing.JLabel FondoRojo5;
    private javax.swing.JLabel FondoRojo6;
    private javax.swing.JLabel FondoRojoR;
    private javax.swing.JLabel FondoRojoRAt;
    private javax.swing.JLabel FondoRojoRAt1;
    private javax.swing.JLabel FondoRojoRAtT;
    private javax.swing.JLabel FondoRojoRB;
    private javax.swing.JLabel FondoRojoRBalerosD;
    private javax.swing.JLabel FondoRojoRBalerosT;
    private javax.swing.JLabel FondoRojoRFD;
    private javax.swing.JLabel FondoRojoRFT;
    private javax.swing.JLabel FondoRojoRLP;
    private javax.swing.JRadioButton RadioAfinacionB;
    private javax.swing.JRadioButton RadioAfinacionM;
    private javax.swing.JRadioButton RadioAfinacionRA;
    private javax.swing.JRadioButton RadioAmortiB;
    private javax.swing.JRadioButton RadioAmortiM;
    private javax.swing.JRadioButton RadioAmortiRA;
    private javax.swing.JRadioButton RadioAteInmed;
    private javax.swing.JRadioButton RadioAtencion;
    private javax.swing.JRadioButton RadioBYPB;
    private javax.swing.JRadioButton RadioBYPM;
    private javax.swing.JRadioButton RadioBYPRA;
    private javax.swing.JRadioButton RadioBaleroRDB;
    private javax.swing.JRadioButton RadioBaleroRDM;
    private javax.swing.JRadioButton RadioBaleroRDRA;
    private javax.swing.JRadioButton RadioBaleroRTB;
    private javax.swing.JRadioButton RadioBaleroRTM;
    private javax.swing.JRadioButton RadioBaleroRTRA;
    private javax.swing.JRadioButton RadioBateriaB;
    private javax.swing.JRadioButton RadioBateriaM;
    private javax.swing.JRadioButton RadioBateriaRA;
    private javax.swing.JRadioButton RadioBuenEstado;
    private javax.swing.JRadioButton RadioDireccionB;
    private javax.swing.JRadioButton RadioDireccionM;
    private javax.swing.JRadioButton RadioDireccionRA;
    private javax.swing.JRadioButton RadioFrenosDB;
    private javax.swing.JRadioButton RadioFrenosDM;
    private javax.swing.JRadioButton RadioFrenosDRA;
    private javax.swing.JRadioButton RadioFrenosTB;
    private javax.swing.JRadioButton RadioFrenosTM;
    private javax.swing.JRadioButton RadioFrenosTRA;
    private javax.swing.JRadioButton RadioLimpiaPB;
    private javax.swing.JRadioButton RadioLimpiaPM;
    private javax.swing.JRadioButton RadioLimpiaPRA;
    private javax.swing.JRadioButton RadioLucesB;
    private javax.swing.JRadioButton RadioLucesM;
    private javax.swing.JRadioButton RadioLucesRA;
    private javax.swing.JRadioButton RadioManguerasB;
    private javax.swing.JRadioButton RadioManguerasM;
    private javax.swing.JRadioButton RadioManguerasRA;
    private javax.swing.JRadioButton RadioNFB;
    private javax.swing.JRadioButton RadioNFM;
    private javax.swing.JRadioButton RadioNFRA;
    private javax.swing.JRadioButton RadioNeumaticosB;
    private javax.swing.JRadioButton RadioNeumaticosM;
    private javax.swing.JRadioButton RadioNeumaticosRA;
    private javax.swing.JRadioButton RadioSistemaEscapeB;
    private javax.swing.JRadioButton RadioSistemaEscapeM;
    private javax.swing.JRadioButton RadioSistemaEscapeRA;
    private javax.swing.JRadioButton RadioSuspencionDB;
    private javax.swing.JRadioButton RadioSuspencionDM;
    private javax.swing.JRadioButton RadioSuspencionDRA;
    private javax.swing.JRadioButton RadioSuspencionTB;
    private javax.swing.JRadioButton RadioSuspencionTM;
    private javax.swing.JRadioButton RadioSuspencionTRA;
    private javax.swing.JLabel Titulo;
    private javax.swing.ButtonGroup buttonGroupAfinacion;
    private javax.swing.ButtonGroup buttonGroupAmortiguadores;
    private javax.swing.ButtonGroup buttonGroupBalerosDeRuedasD;
    private javax.swing.ButtonGroup buttonGroupBalerosDeRuedasT;
    private javax.swing.ButtonGroup buttonGroupBandasYPoleas;
    private javax.swing.ButtonGroup buttonGroupBateria;
    private javax.swing.ButtonGroup buttonGroupDireccion;
    private javax.swing.ButtonGroup buttonGroupEstadoCarro;
    private javax.swing.ButtonGroup buttonGroupFrenosD;
    private javax.swing.ButtonGroup buttonGroupFrenosT;
    private javax.swing.ButtonGroup buttonGroupLimpiaP;
    private javax.swing.ButtonGroup buttonGroupLuces;
    private javax.swing.ButtonGroup buttonGroupMangueras;
    private javax.swing.ButtonGroup buttonGroupNeumaticos;
    private javax.swing.ButtonGroup buttonGroupNivelesFluidos;
    private javax.swing.ButtonGroup buttonGroupSistemaEscape;
    private javax.swing.ButtonGroup buttonGroupSuspencionD;
    private javax.swing.ButtonGroup buttonGroupSuspencionT;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
private javax.swing.JButton BotonBusquedaCliente;
private javax.swing.JTextField EntradaBuscarCliente;

    }
