/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leuraojedamecanicos;


import ConexionBD.ConexionMySQL;
import static java.awt.Color.blue;
import static java.awt.Color.orange;
import static java.awt.Color.red;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gerardo
 */
public final class EstadoCarroModifi extends javax.swing.JFrame {

    /**
     * Creates new form Sprints
     */
    
    public EstadoCarroModifi(int Op,String idInv) {
        initComponents();
        TextID.setText(""+Op);
        ConsultaD(TextID.getText());
        IdIngreso.setText(idInv);
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LogoH.png")));
    }
   
    EstadoCarroModifi() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EtiquetaX2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        EtiquetaX13 = new javax.swing.JLabel();
        EtiquetaFoco2 = new javax.swing.JLabel();
        EtiquetaX12 = new javax.swing.JLabel();
        RadioDefensaDel = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        RadioDefensaTras = new javax.swing.JRadioButton();
        EtiquetaX15 = new javax.swing.JLabel();
        EtiquetaFoco4 = new javax.swing.JLabel();
        RadioFocoIzquiTrase = new javax.swing.JRadioButton();
        RadioFocoDerechoTrase = new javax.swing.JRadioButton();
        EtiquetaX14 = new javax.swing.JLabel();
        EtiquetaFoco3 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        EtiquetaX = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        EtiquetaX3 = new javax.swing.JLabel();
        TextID = new javax.swing.JTextField();
        EtiquetaX4 = new javax.swing.JLabel();
        EtiquetaX5 = new javax.swing.JLabel();
        EtiquetaX6 = new javax.swing.JLabel();
        EtiquetaX7 = new javax.swing.JLabel();
        EtiquetaX8 = new javax.swing.JLabel();
        EtiquetaX9 = new javax.swing.JLabel();
        EtiquetaX10 = new javax.swing.JLabel();
        EtiquetaX11 = new javax.swing.JLabel();
        EtiquetaFoco1 = new javax.swing.JLabel();
        EtiquetaX16 = new javax.swing.JLabel();
        EtiquetaX18 = new javax.swing.JLabel();
        EtiquetaX17 = new javax.swing.JLabel();
        EtiquetaX19 = new javax.swing.JLabel();
        EtiquetaX20 = new javax.swing.JLabel();
        EtiquetaX21 = new javax.swing.JLabel();
        EtiquetaX22 = new javax.swing.JLabel();
        EtiquetaX23 = new javax.swing.JLabel();
        EtiquetaX24 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        IdIngreso = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EtiquetaX2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX2.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 130, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroPuerta90x76.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel3.setText("<HTML>Salpicadera<P> Trasera<P>Derecha<HTML>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 60, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroPueraTraseraIzquierda85x82.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, 83));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SalpicaderaCarro120x67.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroSalpicaderaTraseraIzquierda120x67.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroCofre120x124.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 124));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PlantillaParabrisas78x120.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 70, 130));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroTecho130x93.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 130, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroCajuela120x110.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 120, 120));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroSalpicaderaDerecha120x64.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 120, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroPuertaDerecha90x76.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 100, 80));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroPuertaTraseraDerecha85x82.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 85, 82));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroSalpicaderaTraseraDerecha120x67.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 120, 67));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ParrillaDelanteraFocos120x45.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 120, 50));

        EtiquetaX13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        EtiquetaX13.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 50, 50));

        EtiquetaFoco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroFoco.png"))); // NOI18N
        getContentPane().add(EtiquetaFoco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 40, 30));

        EtiquetaX12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        EtiquetaX12.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 30, 50));
        getContentPane().add(RadioDefensaDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ParrillaTraseraFocos120x50.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 120, 50));
        getContentPane().add(RadioDefensaTras, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, -1, -1));

        EtiquetaX15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        EtiquetaX15.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 50, 50));

        EtiquetaFoco4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroFoco.png"))); // NOI18N
        getContentPane().add(EtiquetaFoco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 40, 30));
        getContentPane().add(RadioFocoIzquiTrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 30, -1));
        getContentPane().add(RadioFocoDerechoTrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, -1, -1));

        EtiquetaX14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        EtiquetaX14.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 50, 50));

        EtiquetaFoco3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroFoco.png"))); // NOI18N
        getContentPane().add(EtiquetaFoco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 40, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/llanta50x4.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/llanta50x4.png"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/llanta50x4.png"))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/llanta50x4.png"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("ESTADO ACTUAL DEL CARRO");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 290, 40));

        jLabel27.setText("<HTML>Puerta<P> Delantera<P>Derecha<HTML>");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        jLabel28.setText("<HTML>Puerta<P> Trasera<P> Izquierda<HTML>");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 60, -1));

        jLabel29.setText("<HTML>Salpicadera<P> Delantera<P> Derecha<HTML>");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 60, -1));

        jLabel30.setText("<HTML>Foco<P> Derecho<P> Delantero<HTML>");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, -1));

        jLabel31.setText("<HTML>Foco<P> Derecho<P> Trasera<HTML>");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Defensa Trasera");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 110, -1));

        jLabel33.setText("<HTML>Foco<P> Izquierdo<P> Delantero<HTML>");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Defensa Delantera");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 110, -1));

        jLabel35.setText("<HTML>Foco<P> Izquierdo<P> Trasera<HTML>");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        jLabel36.setText("Cofre");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel37.setText("Parabrisas");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel38.setText("Techo");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        EtiquetaX.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX.setForeground(new java.awt.Color(255, 51, 0));
        EtiquetaX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, 70));

        jLabel39.setText("<HTML>Parabrisas<P> Trasero<HTML>");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jLabel40.setText("Puerta Cajuela");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 80, 30));

        jLabel41.setText("<HTML>Salpicadera<P> Delantera<P> Izquierda<HTML>");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 60, -1));

        jLabel42.setText("<HTML>Puerta<P> Delantera<P>Derecha<HTML>");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, -1, -1));

        jLabel43.setText("<HTML>Puerta<P> Delantera<P> Izquierda<HTML>");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel44.setText("<HTML>Salpicadera<P> Trasera<P> Izquierda<HTML>");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 60, -1));

        jLabel45.setText("Llanta Tra.Der.");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, -1, -1));

        jLabel46.setText("Llanta Tra.Iz.");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, -1));

        jLabel47.setText("Llanta De.Iz.");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, -1, -1));

        jLabel48.setText("Llanta De.Der.");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, -1, -1));

        EtiquetaX3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX3.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, 90));

        TextID.setEnabled(false);
        getContentPane().add(TextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 60, -1));

        EtiquetaX4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX4.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 100, 90));

        EtiquetaX5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX5.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 120, 90));

        EtiquetaX6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX6.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 140, 80));

        EtiquetaX7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX7.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 90, 80));

        EtiquetaX8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX8.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 80, 80));

        EtiquetaX9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX9.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 120, 80));

        EtiquetaX10.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX10.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 140, 50));

        EtiquetaX11.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX11.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 140, 50));

        EtiquetaFoco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroFoco.png"))); // NOI18N
        getContentPane().add(EtiquetaFoco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 30, 30));

        EtiquetaX16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        EtiquetaX16.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 50, 40));

        EtiquetaX18.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX18.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, 50, 40));

        EtiquetaX17.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX17.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 50, 40));

        EtiquetaX19.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX19.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 50, 40));

        EtiquetaX20.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX20.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 120));

        EtiquetaX21.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX21.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 70, 110));

        EtiquetaX22.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX22.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 120, 100));

        EtiquetaX23.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX23.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 50, 80));

        EtiquetaX24.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        EtiquetaX24.setForeground(new java.awt.Color(255, 0, 0));
        EtiquetaX24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(EtiquetaX24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 60, 100));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 70));

        IdIngreso.setEnabled(false);
        getContentPane().add(IdIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 60, -1));

        jLabel18.setText("Id Diagn.:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jLabel20.setText("Id Ingreso:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        //ModificarIngresoVehiculo MIV=new ModificarIngresoVehiculo(IdIngreso.getText());
        //MIV.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    //OBTENER DATOS DE LOS RADIOS DE LAS IMAGENES 
    
    //////////////////
    void ConsultaD(String Id)
    {
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        //String sql="select * from diagnostico where IdDiagnostico="+"'"+Id+"'";
        ////////////////////////ALERTA CAMBIAR CONSULTA PARA SOLUCIONAR ERROR EN EL BOTON REGRESAR o Agregar otra consulta que recupere o traiga el valor de la tabla del vehiculo registrado
        String sql="select * from estadocarro where IdDiagnostico='"+Id+"';";
        String DiagnosticoE[]=new String[25];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                //Se guarda en el arreglo y del otro lado es la columna del valor
                DiagnosticoE[0]=con.resultado.getString(1);
                DiagnosticoE[1]=con.resultado.getString(2);
                DiagnosticoE[2]=con.resultado.getString(3);
                DiagnosticoE[3]=con.resultado.getString(4);
                DiagnosticoE[4]=con.resultado.getString(5);
                DiagnosticoE[5]=con.resultado.getString(6);
                DiagnosticoE[6]=con.resultado.getString(7);
                DiagnosticoE[7]=con.resultado.getString(8);
                DiagnosticoE[8]=con.resultado.getString(9);
                DiagnosticoE[9]=con.resultado.getString(10);
                DiagnosticoE[10]=con.resultado.getString(11);
                DiagnosticoE[11]=con.resultado.getString(12);
                DiagnosticoE[12]=con.resultado.getString(13);
                DiagnosticoE[13]=con.resultado.getString(14);
                DiagnosticoE[14]=con.resultado.getString(15);
                DiagnosticoE[15]=con.resultado.getString(16);
                DiagnosticoE[16]=con.resultado.getString(17);
                DiagnosticoE[17]=con.resultado.getString(18);
                DiagnosticoE[18]=con.resultado.getString(19);
                DiagnosticoE[19]=con.resultado.getString(20);
                DiagnosticoE[20]=con.resultado.getString(21);
                DiagnosticoE[21]=con.resultado.getString(22);
                DiagnosticoE[22]=con.resultado.getString(23);
                DiagnosticoE[23]=con.resultado.getString(24);
                DiagnosticoE[24]=con.resultado.getString(25);
            }
            
            if("MAL".equals(DiagnosticoE[2]))
            {
             EtiquetaX2.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[3]))
            {
             EtiquetaX3.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[4]))
            {
             EtiquetaX4.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[5]))
            {
             EtiquetaX5.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[6]))
            {
             EtiquetaX6.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[7]))
            {
             EtiquetaX7.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[8]))
            {
             EtiquetaX8.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[9]))
            {
             EtiquetaX9.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[10]))
            {
             EtiquetaX10.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[11]))
            {
             EtiquetaX11.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[12]))
            {
             EtiquetaX12.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[13]))
            {
             EtiquetaX13.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[14]))
            {
             EtiquetaX14.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[15]))
            {
             EtiquetaX15.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[16]))
            {
             EtiquetaX16.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[17]))
            {
             EtiquetaX17.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[18]))
            {
             EtiquetaX18.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[19]))
            {
             EtiquetaX19.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[20]))
            {
             EtiquetaX20.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[21]))
            {
             EtiquetaX21.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[22]))
            {
             EtiquetaX22.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[23]))
            {
             EtiquetaX23.setText("X");   
            }
            if("MAL".equals(DiagnosticoE[24]))
            {
             EtiquetaX24.setText("X");   
            }
            
        } catch (SQLException ex) {
            //Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadoCarroModifi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadoCarroModifi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadoCarroModifi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadoCarroModifi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadoCarroModifi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EtiquetaFoco1;
    private javax.swing.JLabel EtiquetaFoco2;
    private javax.swing.JLabel EtiquetaFoco3;
    private javax.swing.JLabel EtiquetaFoco4;
    private javax.swing.JLabel EtiquetaX;
    private javax.swing.JLabel EtiquetaX10;
    private javax.swing.JLabel EtiquetaX11;
    private javax.swing.JLabel EtiquetaX12;
    private javax.swing.JLabel EtiquetaX13;
    private javax.swing.JLabel EtiquetaX14;
    private javax.swing.JLabel EtiquetaX15;
    private javax.swing.JLabel EtiquetaX16;
    private javax.swing.JLabel EtiquetaX17;
    private javax.swing.JLabel EtiquetaX18;
    private javax.swing.JLabel EtiquetaX19;
    private javax.swing.JLabel EtiquetaX2;
    private javax.swing.JLabel EtiquetaX20;
    private javax.swing.JLabel EtiquetaX21;
    private javax.swing.JLabel EtiquetaX22;
    private javax.swing.JLabel EtiquetaX23;
    private javax.swing.JLabel EtiquetaX24;
    private javax.swing.JLabel EtiquetaX3;
    private javax.swing.JLabel EtiquetaX4;
    private javax.swing.JLabel EtiquetaX5;
    private javax.swing.JLabel EtiquetaX6;
    private javax.swing.JLabel EtiquetaX7;
    private javax.swing.JLabel EtiquetaX8;
    private javax.swing.JLabel EtiquetaX9;
    private javax.swing.JTextField IdIngreso;
    private javax.swing.JRadioButton RadioDefensaDel;
    private javax.swing.JRadioButton RadioDefensaTras;
    private javax.swing.JRadioButton RadioFocoDerechoTrase;
    private javax.swing.JRadioButton RadioFocoIzquiTrase;
    private javax.swing.JTextField TextID;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
