/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leuraojedamecanicos;

import ConexionBD.ConexionMySQL;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gerardo
 */
public class EstadoCarro extends javax.swing.JFrame {

    /**
     * Creates new form Sprints
     */
    
    public EstadoCarro(int Op) {
        initComponents();
        TextID.setText(""+Op);
          this.setLocationRelativeTo(null);
          setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LogoH.png")));
       
    }
   
    EstadoCarro() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RadioSalDeIzq = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        RadioPuertaDeIzq = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RadioPuertaTrasIzquie = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        RadioSalpicaderaTrasIzqui = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        RadioCofre = new javax.swing.JRadioButton();
        RadioParabrisas = new javax.swing.JRadioButton();
        RadioTecho = new javax.swing.JRadioButton();
        PuertaCajuela = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        RadioSalTraDerecha = new javax.swing.JRadioButton();
        RadioPuertaTrasDere = new javax.swing.JRadioButton();
        RadioPuertaDeDer = new javax.swing.JRadioButton();
        RadioSalDeDerecha = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        RadioFocoIzquiDelan = new javax.swing.JRadioButton();
        RadioFocoDereiDelan = new javax.swing.JRadioButton();
        RadioDefensaDel = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        RadioDefensaTras = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        RadioFocoIzquiTrase = new javax.swing.JRadioButton();
        RadioFocoDerechoTrase = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        LLantaDeIz = new javax.swing.JRadioButton();
        LLantaDeDer = new javax.swing.JRadioButton();
        LLantaTraIz = new javax.swing.JRadioButton();
        LLantaTraDere = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        RadioParabrisasTrasero = new javax.swing.JRadioButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        TextID = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(RadioSalDeIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroPuerta90x76.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));
        getContentPane().add(RadioPuertaDeIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        jLabel3.setText("<HTML>Salpicadera<P> Trasera<P>Derecha<HTML>");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 60, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroPueraTraseraIzquierda85x82.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, 83));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SalpicaderaCarro120x67.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        getContentPane().add(RadioPuertaTrasIzquie, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroSalpicaderaTraseraIzquierda120x67.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));
        getContentPane().add(RadioSalpicaderaTrasIzqui, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroCofre120x124.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 120, 124));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PlantillaParabrisas78x120.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 70, 130));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroTecho130x93.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 130, 100));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroCajuela120x110.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 120, 120));
        getContentPane().add(RadioCofre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, -1));
        getContentPane().add(RadioParabrisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, -1, -1));
        getContentPane().add(RadioTecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));
        getContentPane().add(PuertaCajuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroSalpicaderaDerecha120x64.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 530, 120, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroPuertaDerecha90x76.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 100, 80));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroPuertaTraseraDerecha85x82.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 85, 82));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroSalpicaderaTraseraDerecha120x67.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 120, 67));
        getContentPane().add(RadioSalTraDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));
        getContentPane().add(RadioPuertaTrasDere, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, -1, -1));
        getContentPane().add(RadioPuertaDeDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, -1, -1));
        getContentPane().add(RadioSalDeDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 590, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ParrillaDelanteraFocos120x45.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 120, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroFoco.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 40, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroFoco.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 40, 30));
        getContentPane().add(RadioFocoIzquiDelan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 30, -1));
        getContentPane().add(RadioFocoDereiDelan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, -1, -1));
        getContentPane().add(RadioDefensaDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ParrillaTraseraFocos120x50.png"))); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 120, 50));
        getContentPane().add(RadioDefensaTras, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroFoco.png"))); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 40, 30));
        getContentPane().add(RadioFocoIzquiTrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 30, -1));
        getContentPane().add(RadioFocoDerechoTrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroFoco.png"))); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 40, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/llanta50x4.png"))); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/llanta50x4.png"))); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/llanta50x4.png"))); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 560, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/llanta50x4.png"))); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, -1, -1));
        getContentPane().add(LLantaDeIz, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 20, -1));
        getContentPane().add(LLantaDeDer, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, -1, -1));
        getContentPane().add(LLantaTraIz, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, -1, -1));
        getContentPane().add(LLantaTraDere, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 600, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("ESTADO DEL CARRO");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 260, 40));

        jLabel27.setText("<HTML>Puerta<P> Delantera<P>Derecha<HTML>");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 480, -1, -1));

        jLabel28.setText("<HTML>Puerta<P> Trasera<P> Izquierda<HTML>");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 60, -1));

        jLabel29.setText("<HTML>Salpicadera<P> Delantera<P> Derecha<HTML>");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 60, -1));

        jLabel30.setText("<HTML>Foco<P> Derecho<P> Delantero<HTML>");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, -1));

        jLabel31.setText("<HTML>Foco<P> Derecho<P> Trasera<HTML>");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, -1, -1));

        jLabel32.setText("Defensa Delantera");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        jLabel33.setText("<HTML>Foco<P> Izquierdo<P> Delantero<HTML>");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        jLabel34.setText("Defensa Delantera");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        jLabel35.setText("<HTML>Foco<P> Izquierdo<P> Trasera<HTML>");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        jLabel36.setText("Cofre");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel37.setText("Parabrisas");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel38.setText("Techo");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));
        getContentPane().add(RadioParabrisasTrasero, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        jLabel39.setText("<HTML>Parabrisas<P> Trasero<HTML>");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jLabel40.setText("Puerta Cajuela");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 80, 30));

        jLabel41.setText("<HTML>Salpicadera<P> Delantera<P> Izquierda<HTML>");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 60, -1));

        jLabel42.setText("<HTML>Puerta<P> Delantera<P>Derecha<HTML>");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 480, -1, -1));

        jLabel43.setText("<HTML>Puerta<P> Delantera<P> Izquierda<HTML>");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel44.setText("<HTML>Salpicadera<P> Trasera<P> Izquierda<HTML>");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 60, -1));

        jLabel45.setText("Llanta Tra.Der.");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, -1, -1));

        jLabel46.setText("Llanta Tra.Iz.");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, -1));

        jLabel47.setText("Llanta De.Iz.");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, -1, -1));

        jLabel48.setText("Llanta De.Der.");
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, -1, -1));

        Registrar.setText("Registrar Estado");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, 140, 30));

        TextID.setEnabled(false);
        getContentPane().add(TextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 50, 30));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        // TODO add your handling code here:
       ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        int IdDiagnostico=Integer.parseInt(TextID.getText());
        System.out.println(IdDiagnostico);
        String SalpDelIzq=ObtenerDatosRadioSalDeIzq(); 
        String PuerDelIzq=ObtenerDatosRadioPuertaDeIzq();
        String PuerTraIzq=ObtenerDatosRadioPuertaTrasIzquie();
        String SalpTraIzq=ObtenerDatosRadioSalpicaderaTrasIzqui(); 
        String SalpDelDer=ObtenerDatosRadioSalDeDerecha();
        String PuerDelDer=ObtenerDatosRadioPuertaDeDer();
        String PuerTraDer=ObtenerDatosRadioPuertaTrasDere();
        String SalpTraDer=ObtenerDatosRadioSalTraDerecha();
        String DefenDelan=ObtenerDatosRadioDefensaDel();
        String DefenTrase=ObtenerDatosRadioDefensaTras();
        
        String FocIzqDela=ObtenerDatosRadioFocoIzquiDelan();
        String FocDerDela=ObtenerDatosRadioFocoDereiDelan();
        String FocIzqTras=ObtenerDatosRadioFocoIzquiTrase();
        String FocDerTras=ObtenerDatosRadioFocoDerechoTrase();
        String LLanDelIzq=ObtenerDatosRadioLLantaDeIz();
        String LLanDelDer=ObtenerDatosRadioLLantaDeDer();
        String LLanTraIzq=ObtenerDatosRadioLLantaTraIz();
        String LLanTraDer=ObtenerDatosRadioLLantaTraDere();
        
        String Cofre=ObtenerDatosRadioCofre();
        String Parabrisas=ObtenerDatosRadioParabrisas();
        String Techo=ObtenerDatosRadioTecho();
        String ParabrisasTrasero=ObtenerDatosRadioParabrisasTra();
        String Cajuela=ObtenerDatosRadioCajuela();
        con.GuardarEstadoCarro(IdDiagnostico, SalpDelIzq, PuerDelIzq, PuerTraIzq, SalpTraIzq, SalpDelDer, PuerDelDer, PuerTraDer, SalpTraDer, DefenDelan, DefenTrase, FocIzqDela, FocDerDela, FocIzqTras, FocDerTras, LLanDelIzq, LLanDelDer, LLanTraIzq, LLanTraDer, Cofre, Parabrisas, Techo, ParabrisasTrasero,Cajuela);
        this.setVisible(false);
        try {
            con.CerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(EstadoCarro.class.getName()).log(Level.SEVERE, null, ex);
        }
        Menu M= new Menu();
        M.setVisible(true);
    }//GEN-LAST:event_RegistrarActionPerformed
    //OBTENER DATOS DE LOS RADIOS DE LAS IMAGENES 
    public String ObtenerDatosRadioSalDeIzq()
    {
        String EstadoN=null;
        if(RadioSalDeIzq.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    public String ObtenerDatosRadioPuertaDeIzq()
    {
        String EstadoN=null;
        if(RadioPuertaDeIzq.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    
    public String ObtenerDatosRadioPuertaTrasIzquie()
    {
        String EstadoN=null;
        if(RadioPuertaTrasIzquie.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    
    public String ObtenerDatosRadioSalpicaderaTrasIzqui()
    {
        String EstadoN=null;
        if(RadioSalpicaderaTrasIzqui.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    
    public String ObtenerDatosRadioCofre()
    {
        String EstadoN=null;
        if(RadioCofre.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    
    public String ObtenerDatosRadioParabrisas()
    {
        String EstadoN=null;
        if(RadioParabrisas.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    
    public String ObtenerDatosRadioTecho()
    {
        String EstadoN=null;
        if(RadioTecho.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    
    public String ObtenerDatosRadioParabrisasTra()
    {
        String EstadoN=null;
        if(RadioParabrisasTrasero.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    public String ObtenerDatosRadioSalTraDerecha()
    {
        String EstadoN=null;
        if(RadioSalTraDerecha.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    
    public String ObtenerDatosRadioPuertaTrasDere()
    {
        String EstadoN=null;
        if(RadioPuertaTrasDere.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    public String ObtenerDatosRadioPuertaDeDer()
    {
        String EstadoN=null;
        if(RadioPuertaDeDer.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    
    public String ObtenerDatosRadioSalDeDerecha()
    {
        String EstadoN=null;
        if(RadioSalDeDerecha.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    
    public String ObtenerDatosRadioFocoIzquiDelan()
    {
        String EstadoN=null;
        if(RadioFocoIzquiDelan.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    public String ObtenerDatosRadioFocoDereiDelan()
    {
        String EstadoN=null;
        if(RadioFocoDereiDelan.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    public String ObtenerDatosRadioDefensaDel()
    {
        String EstadoN=null;
        if(RadioDefensaDel.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    public String ObtenerDatosRadioFocoIzquiTrase()
    {
        String EstadoN=null;
        if(RadioFocoIzquiTrase.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    public String ObtenerDatosRadioFocoDerechoTrase()
    {
        String EstadoN=null;
        if(RadioFocoDerechoTrase.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    
    public String ObtenerDatosRadioDefensaTras()
    {
        String EstadoN=null;
        if(RadioDefensaTras.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
   
    public String ObtenerDatosRadioLLantaDeIz()
    {
        String EstadoN=null;
        if(LLantaDeIz.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    public String ObtenerDatosRadioLLantaDeDer()
    {
        String EstadoN=null;
        if(LLantaDeDer.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    public String ObtenerDatosRadioLLantaTraIz()
    {
        String EstadoN=null;
        if(LLantaTraIz.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    public String ObtenerDatosRadioLLantaTraDere()
    {
        String EstadoN=null;
        if(LLantaTraDere.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    
    public String ObtenerDatosRadioCajuela()
    {
        String EstadoN=null;
        if(LLantaTraDere.isSelected())
            {
            EstadoN="MAL";
            }
        if(EstadoN==null)
            {
           EstadoN="BIEN";
            }
        return EstadoN;
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadoCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadoCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadoCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadoCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadoCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton LLantaDeDer;
    private javax.swing.JRadioButton LLantaDeIz;
    private javax.swing.JRadioButton LLantaTraDere;
    private javax.swing.JRadioButton LLantaTraIz;
    private javax.swing.JRadioButton PuertaCajuela;
    private javax.swing.JRadioButton RadioCofre;
    private javax.swing.JRadioButton RadioDefensaDel;
    private javax.swing.JRadioButton RadioDefensaTras;
    private javax.swing.JRadioButton RadioFocoDerechoTrase;
    private javax.swing.JRadioButton RadioFocoDereiDelan;
    private javax.swing.JRadioButton RadioFocoIzquiDelan;
    private javax.swing.JRadioButton RadioFocoIzquiTrase;
    private javax.swing.JRadioButton RadioParabrisas;
    private javax.swing.JRadioButton RadioParabrisasTrasero;
    private javax.swing.JRadioButton RadioPuertaDeDer;
    private javax.swing.JRadioButton RadioPuertaDeIzq;
    private javax.swing.JRadioButton RadioPuertaTrasDere;
    private javax.swing.JRadioButton RadioPuertaTrasIzquie;
    private javax.swing.JRadioButton RadioSalDeDerecha;
    private javax.swing.JRadioButton RadioSalDeIzq;
    private javax.swing.JRadioButton RadioSalTraDerecha;
    private javax.swing.JRadioButton RadioSalpicaderaTrasIzqui;
    private javax.swing.JRadioButton RadioTecho;
    private javax.swing.JButton Registrar;
    private javax.swing.JTextField TextID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
