/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leuraojedamecanicos;


import ConexionBD.ConexionMySQL;
import static java.awt.Color.*;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mecanicos.SoloMayusculas;

/**
 *
 * @author Gerardo
 */
public final class ModificarIngresoVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form Nota
     */
      
    public ModificarIngresoVehiculo(String idv) {
        initComponents();
        EtiquetaNotaN.setText(""+idv);
        this.setLocationRelativeTo(null);
        EntradaVehiculo.setDocument(new SoloMayusculas());
        RegistroDeVehiculosIngresados mod=new RegistroDeVehiculosIngresados();
        System.out.println("El id que se trajo es:"+mod.llevarId());
        Llenado(idv);
    }

    private ModificarIngresoVehiculo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Titulo = new javax.swing.JLabel();
        EXIT = new javax.swing.JButton();
        EntradaCliente = new javax.swing.JTextField();
        EntradaDireccionC = new javax.swing.JTextField();
        EntradaTEL = new javax.swing.JTextField();
        EntradaTecnico = new javax.swing.JTextField();
        EntradaVehiculo = new javax.swing.JTextField();
        EntradaPlaca = new javax.swing.JTextField();
        EntradaSerie = new javax.swing.JTextField();
        EntradaKm = new javax.swing.JTextField();
        EtiquetaFecha = new javax.swing.JLabel();
        EtiquetaKM = new javax.swing.JLabel();
        EtiquetaPlaca = new javax.swing.JLabel();
        EtiquetaVehiculo = new javax.swing.JLabel();
        EtiquetaTEL = new javax.swing.JLabel();
        EtiquetaCliente = new javax.swing.JLabel();
        EtiquetaDireccion = new javax.swing.JLabel();
        EtiquetaTecnico = new javax.swing.JLabel();
        EtiquetaSerie = new javax.swing.JLabel();
        EtiquetaTCofre = new javax.swing.JLabel();
        EtiquetaInspe = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BotonActualizarDatosReg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EntradaTCofreAb = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        EntradaObservaciones = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        EtiquetaNotaN = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        EntradaNeumaticos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EntradaFD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        EntradaFT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EntradaAmor = new javax.swing.JTextField();
        EntradaSusD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EntradaSusT = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        EntradaLuces = new javax.swing.JTextField();
        EntradaAfinacion = new javax.swing.JTextField();
        EntradaMangueras = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        EntradaDeF = new javax.swing.JTextField();
        EntradaDireccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        EntradaLP = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        EntradaBat = new javax.swing.JTextField();
        EntradaBalerosT = new javax.swing.JTextField();
        EntradaBalerosD = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        EntradaSistemaE = new javax.swing.JTextField();
        EntradasBandasyP = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        EntradaId = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        EntradaApellidop = new javax.swing.JTextField();
        EntradaApellidoM = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        EtiquetaGasolina2 = new javax.swing.JLabel();
        SlGasolina2 = new javax.swing.JSlider();
        EtiquetaGasolinaPorcentaje = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        PanelEstadoVehiculo = new javax.swing.JPanel();
        EtiquetaEstadoDelVehiculo = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        EntradaIdVehiculo = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        FechaIngresoVehiculo = new javax.swing.JTextField();
        EntradaFechaDiagnostico = new javax.swing.JTextField();
        RadioBuenEstado = new javax.swing.JRadioButton();
        RadioAtencion = new javax.swing.JRadioButton();
        RadioAteInmed = new javax.swing.JRadioButton();
        IdIngresoVehiculo = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();
        EntradaEstadoVehiuculooo = new javax.swing.JTextField();
        EntradaIdDiagnostico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Modificacion de Ingreso de Vehículos");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 700, 40));

        EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        EXIT.setBorder(null);
        EXIT.setBorderPainted(false);
        EXIT.setContentAreaFilled(false);
        EXIT.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        EXIT.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida (1).png"))); // NOI18N
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 90, 70));

        EntradaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaClienteActionPerformed(evt);
            }
        });
        getContentPane().add(EntradaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 150, -1));

        EntradaDireccionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaDireccionCActionPerformed(evt);
            }
        });
        getContentPane().add(EntradaDireccionC, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 110, -1));

        EntradaTEL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaTELKeyTyped(evt);
            }
        });
        getContentPane().add(EntradaTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 110, -1));
        getContentPane().add(EntradaTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 110, -1));
        getContentPane().add(EntradaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 110, -1));
        getContentPane().add(EntradaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 110, -1));
        getContentPane().add(EntradaSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 110, -1));

        EntradaKm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaKmKeyTyped(evt);
            }
        });
        getContentPane().add(EntradaKm, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 110, -1));

        EtiquetaFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaFecha.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaFecha.setText("Fecha Diagnostico:");
        getContentPane().add(EtiquetaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 110, 20));

        EtiquetaKM.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaKM.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaKM.setText("KM/MILLAS:");
        getContentPane().add(EtiquetaKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 70, 20));

        EtiquetaPlaca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaPlaca.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaPlaca.setText("Placa:");
        getContentPane().add(EtiquetaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 80, 20));

        EtiquetaVehiculo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaVehiculo.setText("Vehículo:");
        getContentPane().add(EtiquetaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 80, 20));

        EtiquetaTEL.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaTEL.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaTEL.setText("TEL:");
        getContentPane().add(EtiquetaTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 80, 20));

        EtiquetaCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaCliente.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaCliente.setText("Cliente:");
        getContentPane().add(EtiquetaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, 30));

        EtiquetaDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaDireccion.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaDireccion.setText("Direccion:");
        getContentPane().add(EtiquetaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 70, 30));

        EtiquetaTecnico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaTecnico.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaTecnico.setText("Tecnico:");
        getContentPane().add(EtiquetaTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 80, 30));

        EtiquetaSerie.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaSerie.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaSerie.setText("Serie:");
        getContentPane().add(EtiquetaSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 60, 20));

        EtiquetaTCofre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaTCofre.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaTCofre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaTCofre.setText("Inspeccion a cofre abierto");
        getContentPane().add(EtiquetaTCofre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 260, -1));

        EtiquetaInspe.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaInspe.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaInspe.setText("Inspeccion Puntos Basicos De seguridad:");
        getContentPane().add(EtiquetaInspe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Observaciones y Puntos Adicionales");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 260, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 710, 50, 10));

        BotonActualizarDatosReg.setText("Actualizar Datos Del Registro");
        BotonActualizarDatosReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarDatosRegActionPerformed(evt);
            }
        });
        getContentPane().add(BotonActualizarDatosReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 190, 40));

        EntradaTCofreAb.setColumns(20);
        EntradaTCofreAb.setRows(5);
        jScrollPane1.setViewportView(EntradaTCofreAb);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 270, 100));

        EntradaObservaciones.setColumns(20);
        EntradaObservaciones.setRows(5);
        jScrollPane2.setViewportView(EntradaObservaciones);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 1170, 90));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Número De Registro de Vehículo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 210, 60));

        EtiquetaNotaN.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaNotaN.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(EtiquetaNotaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 210, 80, 60));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        Back.setBorder(null);
        Back.setBorderPainted(false);
        Back.setContentAreaFilled(false);
        Back.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        Back.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso (1).png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 60));
        getContentPane().add(EntradaNeumaticos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 110, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Neumaticos:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 70, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Frenos Delanteros:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 20));
        getContentPane().add(EntradaFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 110, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Frenos Traseros:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));
        getContentPane().add(EntradaFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 110, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Amortiguadores:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 120, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Suspencion Delantera:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 150, -1));

        EntradaAmor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaAmorActionPerformed(evt);
            }
        });
        getContentPane().add(EntradaAmor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 110, -1));
        getContentPane().add(EntradaSusD, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 110, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Suspencion Trasera:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 140, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Direccion:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 60, -1));
        getContentPane().add(EntradaSusT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 110, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Bandas y poleas de acc.:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 140, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mangueras:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 70, -1));
        getContentPane().add(EntradaLuces, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 410, 120, -1));
        getContentPane().add(EntradaAfinacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, 110, -1));
        getContentPane().add(EntradaMangueras, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 440, 110, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Niveles de Fluidos:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 380, 120, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Luces:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 50, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Limpia Parabrisas:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        EntradaDeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaDeFActionPerformed(evt);
            }
        });
        getContentPane().add(EntradaDeF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 380, 120, -1));
        getContentPane().add(EntradaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 110, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Bateria:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));
        getContentPane().add(EntradaLP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 110, -1));

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Baleros de Rueda Dela:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 160, -1));

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Baleros de Rueda Tras. :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 160, -1));
        getContentPane().add(EntradaBat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 110, -1));
        getContentPane().add(EntradaBalerosT, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 110, -1));
        getContentPane().add(EntradaBalerosD, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 110, -1));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Sistema de Escape:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 110, -1));

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Afinacion:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 60, -1));
        getContentPane().add(EntradaSistemaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, 110, -1));

        EntradasBandasyP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradasBandasyPActionPerformed(evt);
            }
        });
        getContentPane().add(EntradasBandasyP, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 110, -1));

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Id Cliente:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, 30));
        getContentPane().add(EntradaId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 110, -1));

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("ApellidoP:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, 30));

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("ApellidoM:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 60, 30));
        getContentPane().add(EntradaApellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 150, -1));
        getContentPane().add(EntradaApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 150, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EtiquetaGasolina2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MedidorGasolinaHorizontal200.png"))); // NOI18N
        jPanel1.add(EtiquetaGasolina2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, 60));

        SlGasolina2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SlGasolina2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SlGasolina2StateChanged(evt);
            }
        });
        jPanel1.add(SlGasolina2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, -1));

        EtiquetaGasolinaPorcentaje.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(EtiquetaGasolinaPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 130, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 230, 110));

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Ingresar el estado del tanque de la gasolina");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 270, 20));

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Estado del vehiculo:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 150, 30));

        EtiquetaEstadoDelVehiculo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EtiquetaEstadoDelVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelEstadoVehiculoLayout = new javax.swing.GroupLayout(PanelEstadoVehiculo);
        PanelEstadoVehiculo.setLayout(PanelEstadoVehiculoLayout);
        PanelEstadoVehiculoLayout.setHorizontalGroup(
            PanelEstadoVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadoVehiculoLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(EtiquetaEstadoDelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        PanelEstadoVehiculoLayout.setVerticalGroup(
            PanelEstadoVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstadoVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaEstadoDelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(PanelEstadoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 320, 60));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Id Vehículo:");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 70, 40));
        getContentPane().add(EntradaIdVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 110, -1));

        jLabel31.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("<html>Fecha de Ingreso <p>del vehículo:<html>");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 100, -1));
        getContentPane().add(FechaIngresoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, 120, -1));
        getContentPane().add(EntradaFechaDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 90, 120, -1));

        RadioBuenEstado.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RadioBuenEstado);
        RadioBuenEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioBuenEstado.setText("Buenas Condiciones");
        getContentPane().add(RadioBuenEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 160, 40));

        RadioAtencion.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RadioAtencion);
        RadioAtencion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioAtencion.setText("Requiere Atención");
        getContentPane().add(RadioAtencion, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, 150, 40));

        RadioAteInmed.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(RadioAteInmed);
        RadioAteInmed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RadioAteInmed.setText("Atencion Inmediata");
        getContentPane().add(RadioAteInmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 300, 160, 40));
        getContentPane().add(IdIngresoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, 60, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde-html (1).jpg"))); // NOI18N
        jLabel29.setText("jLabel27");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 180, 60));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoNaranjaClaroEstadoVehiculo.jpg"))); // NOI18N
        jLabel32.setText("jLabel27");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 170, 60));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoRojoEstadoVehiculo.jpg"))); // NOI18N
        jLabel33.setText("jLabel27");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 290, 180, 60));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 610, 80));

        jButton2.setText("Ver Estado del carro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 660, 150, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo5.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 720));

        EntradaEstadoVehiuculooo.setText("jTextField1");
        getContentPane().add(EntradaEstadoVehiuculooo, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, -1, -1));

        EntradaIdDiagnostico.setText("jTextField1");
        getContentPane().add(EntradaIdDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntradaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaClienteActionPerformed

    private void EntradaDireccionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaDireccionCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaDireccionCActionPerformed

    private void BotonActualizarDatosRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarDatosRegActionPerformed
        int idcliente=Integer.parseInt(EntradaId.getText());
        int idvehiculo=Integer.parseInt(EntradaIdVehiculo.getText());
        int idDiagnostico=Integer.parseInt(EntradaIdDiagnostico.getText());
        //int iddiagnostico=Integer.parseInt(EntradaIdDiagnostico.getText());
        int km=Integer.parseInt(EntradaKm.getText());
        String Tanque= String.valueOf(SlGasolina2.getValue());
        String EstadoCarro= EstadoCarro();
        //java.util.Date DateI = FechaIngresovehiculo.getDate();
        //long di=DateI.getTime();
        //java.sql.Date fechaingreso = new java.sql.Date(di);
        //
        //Date fecha=CambioStrinADate(EntradaFechaDiagnostico.getText());
        //Date fechaI=CambioStrinADate(FechaIngresoVehiculo.getText());
        ConexionMySQL Con=new ConexionMySQL();
        Con.ConectarBasedeDatos();
         //METODO PARA Actualizar valores Todos Los valores de aqui
        Con.UpdateDiagnostico(EntradaTCofreAb.getText(),EstadoCarro,EntradaNeumaticos.getText(), EntradaFD.getText(),EntradaFT.getText(),EntradaAmor.getText(),EntradaSusD.getText(), EntradaSusT.getText(),EntradaDireccion.getText(),EntradasBandasyP.getText(), EntradaMangueras.getText(),EntradaDeF.getText(), EntradaLuces.getText(),EntradaLP.getText(),EntradaBat.getText(),EntradaBalerosD.getText(),EntradaBalerosT.getText(),EntradaSistemaE.getText(),EntradaAfinacion.getText(),EntradaObservaciones.getText(), EntradaTecnico.getText(),EntradaFechaDiagnostico.getText(),idDiagnostico);
        //Con.UpdateDiagnostico(,,,,,,,,,,,,,,,,EntradaTecnico.getText(),EntradaFechaDiagnostico.getText(),idcliente);
        Con.UpdateIngresarVehiculo(km, Tanque, FechaIngresoVehiculo.getText(),idDiagnostico);
        try {
            //on.Guardar(ID,EntradaCliente.getText(),EntradaDireccionC.getText(),EntradaDireccionC.getText(),telefono,EntradaVehiculo.getText(),EntradaPlaca.getText(),fecha,EntradaSerie.getText(),KM,Tanque,EntradaTCofreAb.getText(),Estado,EntradaNeumaticos.getText(),FD,FT,AM,SUS,SUST,DI,BA,MAN,FLU,LU,LI,BAT,BALD,BALT,SISE,AFI,EntradaObservaciones.getText());
            //Con.GuardarIngresoVehiculo(idcliente,idvehiculo,iddiagnostico,km,Tanque,fechaingreso);
            Con.CerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(ModificarIngresoVehiculo.class.getName()).log(Level.SEVERE, null, ex);
        }
        Menu M= new Menu();
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonActualizarDatosRegActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        RegistroDeVehiculosIngresados modific=new RegistroDeVehiculosIngresados();
        modific.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void EntradaAmorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaAmorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaAmorActionPerformed

    private void EntradasBandasyPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradasBandasyPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradasBandasyPActionPerformed

    private void EntradaDeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaDeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaDeFActionPerformed

    private void SlGasolina2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SlGasolina2StateChanged
        // TODO add your handling code here:
        EtiquetaGasolinaPorcentaje.setText("<html>Gasolina:<p>"+"  "+SlGasolina2.getValue()+"%"+"<html>");
    }//GEN-LAST:event_SlGasolina2StateChanged

    private void EntradaTELKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaTELKeyTyped
        // TODO add your handling code here:
    if(EntradaTEL.getText().length()>=10){
        evt.consume();
        getToolkit().beep();
    }else{
        char car = evt.getKeyChar();
    if(Character.isDigit(car)){
    }else{
    evt.consume();
    }
    }
    }//GEN-LAST:event_EntradaTELKeyTyped

    private void EntradaKmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaKmKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
    if(Character.isDigit(car)){
    }else{
    evt.consume();
    }
    }//GEN-LAST:event_EntradaKmKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int ID=Integer.parseInt(EntradaIdDiagnostico.getText());
        String idIngreso=IdIngresoVehiculo.getText();
        EstadoCarroModifi ECM=new EstadoCarroModifi(ID,idIngreso);
        ECM.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "WARNING",JOptionPane.WARNING_MESSAGE,
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        // Instrucciones si verdadero
        System.exit(0);
        } else {
            // Instrucciones si falso

        }
    }//GEN-LAST:event_EXITActionPerformed
////Metodo para obtener valor de Los botones de radio "Estado Del vehiculo
   public Date CambioStrinADate(String fecha)
   {
       SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy"); 
            try {
                Date Fecha = (Date) formato.parse(fecha);
                
            } catch (ParseException ex) {
                Logger.getLogger(ModificarIngresoVehiculo.class.getName()).log(Level.SEVERE, null, ex);
            }
        Date Fecha = null;
            return Fecha;
   }
    public void Llenado(String Id)
    {
        //29
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        //String sql="select * from diagnostico where IdDiagnostico="+"'"+Id+"'";
        String sql="select diagnostico.IdDiagnostico,ingresarvehiculos.IdIngresoVehiculo,diagnostico.NumeroCliente,diagnostico.NumeroVehiculo,diagnostico.Inspeccion_Cofre_Abierto,diagnostico.EstadoVehiculo,diagnostico.Neumaticos,diagnostico.FrenosDelanteros,diagnostico.FrenosTraseros,diagnostico.Amortiguadores,diagnostico.SuspencionDelantera,diagnostico.SuspencionTrasera,diagnostico.Direccion,diagnostico.BandasYPoleasDeAccion,diagnostico.Mangueras,diagnostico.NivelesDeFluidos,diagnostico.Luces,diagnostico.LimpiaParabrisas,diagnostico.Bateria,diagnostico.BalerosDeRuedasD,diagnostico.BalerosDeRuedasT,diagnostico.SistemaDeEscape,diagnostico.Afinacion,diagnostico.ObservacionesYPuntosAdicionales,diagnostico.Tecnico,diagnostico.FechaDiagnostico,Ingresarvehiculos.KM_MILLAS,ingresarvehiculos.EstadoTanque,ingresarvehiculos.FechaIngreso from diagnostico,ingresarvehiculos where diagnostico.IdDiagnostico=ingresarvehiculos.NumeroDiagnostico and ingresarvehiculos.IdIngresoVehiculo='"+Id+"';";
        String Diagnostico[]=new String[29];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                //Se guarda en el arreglo y del otro lado es la columna del valor
                Diagnostico[0]=con.resultado.getString(1);
                Diagnostico[1]=con.resultado.getString(2);
                Diagnostico[2]=con.resultado.getString(3);
                Diagnostico[3]=con.resultado.getString(4);
                Diagnostico[4]=con.resultado.getString(5);
                Diagnostico[5]=con.resultado.getString(6);
                Diagnostico[6]=con.resultado.getString(7);
                Diagnostico[7]=con.resultado.getString(8);
                Diagnostico[8]=con.resultado.getString(9);
                Diagnostico[9]=con.resultado.getString(10);
                Diagnostico[10]=con.resultado.getString(11);
                Diagnostico[11]=con.resultado.getString(12);
                Diagnostico[12]=con.resultado.getString(13);
                Diagnostico[13]=con.resultado.getString(14);
                Diagnostico[14]=con.resultado.getString(15);
                Diagnostico[15]=con.resultado.getString(16);
                Diagnostico[16]=con.resultado.getString(17);
                Diagnostico[17]=con.resultado.getString(18);
                Diagnostico[18]=con.resultado.getString(19);
                Diagnostico[19]=con.resultado.getString(20);
                Diagnostico[20]=con.resultado.getString(21);
                Diagnostico[21]=con.resultado.getString(22);
                Diagnostico[22]=con.resultado.getString(23);
                Diagnostico[23]=con.resultado.getString(24);
                Diagnostico[24]=con.resultado.getString(25);
                Diagnostico[25]=con.resultado.getString(26);
                Diagnostico[26]=con.resultado.getString(27);
                Diagnostico[27]=con.resultado.getString(28);
                Diagnostico[28]=con.resultado.getString(29);
            }
            EntradaIdDiagnostico.setText(Diagnostico[0]);
            String idingresoVehiculo=Diagnostico[1];
            IdIngresoVehiculo.setText(idingresoVehiculo);
            String NCliente=Diagnostico[2];
            String NVehiculo=Diagnostico[3];
            EntradaTCofreAb.setText(Diagnostico[4]);
            //Jugar con el campo siguiente para el jpanel cambie de color
            EtiquetaEstadoDelVehiculo.setText(Diagnostico[5]);
            //EntradaEstadoVehiuculooo.setText(Diagnostico[5]);
            if(EtiquetaEstadoDelVehiculo.getText().equals("Requiere atencion"))
            {
                PanelEstadoVehiculo.setBackground(orange);
            }
            if(EtiquetaEstadoDelVehiculo.getText().equals("Buenas condiciones"))
            {
                PanelEstadoVehiculo.setBackground(green);
            }
            if(EtiquetaEstadoDelVehiculo.getText().equals("Atencion Inmediata"))
            {
                PanelEstadoVehiculo.setBackground(red);
            }
            EntradaNeumaticos.setText(Diagnostico[6]);
            EntradaFD.setText(Diagnostico[7]);
            EntradaFT.setText(Diagnostico[8]);
            EntradaAmor.setText(Diagnostico[9]);
            EntradaSusD.setText(Diagnostico[10]);
            EntradaSusT.setText(Diagnostico[11]);
            EntradaDireccion.setText(Diagnostico[12]);
            EntradasBandasyP.setText(Diagnostico[13]);
            EntradaMangueras.setText(Diagnostico[14]);
            EntradaDeF.setText(Diagnostico[15]);
            EntradaLuces.setText(Diagnostico[16]);
            EntradaLP.setText(Diagnostico[17]);
            EntradaBat.setText(Diagnostico[18]);
            EntradaBalerosD.setText(Diagnostico[19]);
            EntradaBalerosT.setText(Diagnostico[20]);
            EntradaSistemaE.setText(Diagnostico[21]);
            EntradaAfinacion.setText(Diagnostico[22]);
            EntradaObservaciones.setText(Diagnostico[23]);
            EntradaTecnico.setText(Diagnostico[24]);
            EntradaFechaDiagnostico.setText(Diagnostico[25]);
            EntradaKm.setText(Diagnostico[26]);
            EtiquetaGasolinaPorcentaje.setText("<html>Gasolina:<p>"+"  "+Diagnostico[27]+"%"+"<html>");
            FechaIngresoVehiculo.setText(Diagnostico[28]);
            con.ConectarBasedeDatos();
            RellenarCamposCliente(NCliente);
            con.ConectarBasedeDatos();
            RellenarCamposVehiculo(NVehiculo);
        } catch (SQLException ex) {
            //Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    public String Mostrar(String Nombre)
    {
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        int i=0;
        String sql="";
        if(Nombre.equals(""))
        {
           sql="SELECT * FROM cliente"; 
        }else{
            sql="SELECT * from cliente Where Nombre like'%"+Nombre+"%'";
        }
        String Usuarios[]=new String[3];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                Usuarios[0]=con.resultado.getString(2);
                Usuarios[1]=con.resultado.getString(5);
                Usuarios[2]=con.resultado.getString(6);
                
            }
            
        } catch (SQLException ex) {
            //Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
        return Usuarios[i];
    }
    
    
    public String ObtenerNumeroNota()
    {
        String id = null;
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        PreparedStatement ps;
        try {
            ps=con.conexion.prepareStatement("select IdIngresoVehiculo from ingresarvehiculos order by IdIngresoVehiculo desc");
            con.resultado=ps.executeQuery();
            if(con.resultado.next())
            {
                //variable donde se va a guardar y el renglon de la tabla del que queremos el dato
            id=con.resultado.getString("IdIngresoVehiculo");
            System.out.println(id);
            }else
            {
                id="0";
            }
            
        } catch (SQLException ex) {
           // Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
   
    public void RellenarCamposCliente(String id)
    {
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        String sql="select * from cliente where IdCliente="+"'"+id+"'";
        String Usuarios[]=new String[6];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                //Se guarda en el arreglo y del otro lado es la columna del valor
                Usuarios[0]=con.resultado.getString(1);
                Usuarios[1]=con.resultado.getString(2);
                Usuarios[2]=con.resultado.getString(3);
                Usuarios[3]=con.resultado.getString(4);
                Usuarios[4]=con.resultado.getString(5);
                Usuarios[5]=con.resultado.getString(6);
            }
            EntradaId.setText(Usuarios[0]);
            EntradaCliente.setText(Usuarios[1]);
            EntradaApellidop.setText(Usuarios[2]);
            EntradaApellidoM.setText(Usuarios[3]);
            EntradaDireccionC.setText(Usuarios[4]);
            EntradaTEL.setText(Usuarios[5]);
            
        } catch (SQLException ex) {
           // Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    public String EstadoCarro()
    {
        String Estado2 = null;
        
        
        if(RadioBuenEstado.isSelected())
        {
            Estado2="Buenas condiciones";
        }//else{JOptionPane.showMessageDialog(null,"Falta de seleccion de valores");}
        if(RadioAtencion.isSelected())
        {
           Estado2="Requiere atencion"; 
        }
        if(RadioAteInmed.isSelected())
        {
           Estado2="Atencion Inmediata"; 
        }
        if(Estado2==null)
        {
           System.out.println("Rquieres selccionar un campo en Estado del vehiculo"); 
           JOptionPane.showMessageDialog(null,"¡ALERTA no se cambiara el estado del vehiculo Seleccione uno si desea cambiarlo!");
        }
        return Estado2;
        
    }
    
    public void RellenarCamposVehiculo(String id)
    {
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        String sql="select * from vehiculos where IdVehiculos="+"'"+id+"'";
        String Usuarios[]=new String[5];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                //Se guarda en el arreglo y del otro lado es la columna del valor
                Usuarios[0]=con.resultado.getString(1);
                Usuarios[1]=con.resultado.getString(2);
                Usuarios[2]=con.resultado.getString(3);
                Usuarios[3]=con.resultado.getString(4);
                Usuarios[4]=con.resultado.getString(5);
               
            }
            EntradaIdVehiculo.setText(Usuarios[0]);
            EntradaVehiculo.setText(Usuarios[2]);
            EntradaSerie.setText(Usuarios[3]);
            EntradaPlaca.setText(Usuarios[4]);
            
            
        } catch (SQLException ex) {
            //Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run()
            {
                
                new ModificarIngresoVehiculo().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton BotonActualizarDatosReg;
    private javax.swing.JButton EXIT;
    private javax.swing.JTextField EntradaAfinacion;
    private javax.swing.JTextField EntradaAmor;
    private javax.swing.JTextField EntradaApellidoM;
    private javax.swing.JTextField EntradaApellidop;
    private javax.swing.JTextField EntradaBalerosD;
    private javax.swing.JTextField EntradaBalerosT;
    private javax.swing.JTextField EntradaBat;
    private javax.swing.JTextField EntradaCliente;
    private javax.swing.JTextField EntradaDeF;
    private javax.swing.JTextField EntradaDireccion;
    private javax.swing.JTextField EntradaDireccionC;
    private javax.swing.JTextField EntradaEstadoVehiuculooo;
    private javax.swing.JTextField EntradaFD;
    private javax.swing.JTextField EntradaFT;
    private javax.swing.JTextField EntradaFechaDiagnostico;
    private javax.swing.JTextField EntradaId;
    private javax.swing.JTextField EntradaIdDiagnostico;
    private javax.swing.JTextField EntradaIdVehiculo;
    private javax.swing.JTextField EntradaKm;
    private javax.swing.JTextField EntradaLP;
    private javax.swing.JTextField EntradaLuces;
    private javax.swing.JTextField EntradaMangueras;
    private javax.swing.JTextField EntradaNeumaticos;
    private javax.swing.JTextArea EntradaObservaciones;
    private javax.swing.JTextField EntradaPlaca;
    private javax.swing.JTextField EntradaSerie;
    private javax.swing.JTextField EntradaSistemaE;
    private javax.swing.JTextField EntradaSusD;
    private javax.swing.JTextField EntradaSusT;
    private javax.swing.JTextArea EntradaTCofreAb;
    private javax.swing.JTextField EntradaTEL;
    private javax.swing.JTextField EntradaTecnico;
    private javax.swing.JTextField EntradaVehiculo;
    private javax.swing.JTextField EntradasBandasyP;
    private javax.swing.JLabel EtiquetaCliente;
    private javax.swing.JLabel EtiquetaDireccion;
    private javax.swing.JLabel EtiquetaEstadoDelVehiculo;
    private javax.swing.JLabel EtiquetaFecha;
    private javax.swing.JLabel EtiquetaGasolina2;
    private javax.swing.JLabel EtiquetaGasolinaPorcentaje;
    private javax.swing.JLabel EtiquetaInspe;
    private javax.swing.JLabel EtiquetaKM;
    private javax.swing.JLabel EtiquetaNotaN;
    private javax.swing.JLabel EtiquetaPlaca;
    private javax.swing.JLabel EtiquetaSerie;
    private javax.swing.JLabel EtiquetaTCofre;
    private javax.swing.JLabel EtiquetaTEL;
    private javax.swing.JLabel EtiquetaTecnico;
    private javax.swing.JLabel EtiquetaVehiculo;
    private javax.swing.JTextField FechaIngresoVehiculo;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField IdIngresoVehiculo;
    private javax.swing.JPanel PanelEstadoVehiculo;
    private javax.swing.JRadioButton RadioAteInmed;
    private javax.swing.JRadioButton RadioAtencion;
    private javax.swing.JRadioButton RadioBuenEstado;
    private javax.swing.JSlider SlGasolina2;
    private javax.swing.JLabel Titulo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
private javax.swing.JButton BotonBusquedaCliente;
private javax.swing.JTextField EntradaBuscarCliente;

    }
