/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leuraojedamecanicos;


import ConexionBD.ConexionMySQL;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import mecanicos.SoloMayusculas;

/**
 *
 * @author Gerardo
 */
public final class NotaEdicion extends javax.swing.JFrame {

    /**
     * Creates new form Nota
     */
    public NotaEdicion(String Id) {
        initComponents();
        System.out.println("Dato obtenido:"+Id);
        //Mostrar("");
        this.setLocationRelativeTo(null);
        //EntradaPlaca.setDocument(new SoloMayusculas());
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LogoH.png")));
        ID.setText(Id);
        RellenoDtos(Id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        EtiquetaNotas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EntradaManoDeObra = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        EntradaRefaccionesT = new javax.swing.JTextArea();
        EntradaManoDeObraD = new javax.swing.JTextField();
        EntradaCostoR = new javax.swing.JTextField();
        EdicionNota = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EntradaNombre = new javax.swing.JTextField();
        EntradaIdCliente = new javax.swing.JTextField();
        EntradaApellidoP = new javax.swing.JTextField();
        EntradaIdVehiculo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        EntradaApellidoM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        EntradaVehiculo = new javax.swing.JTextField();
        Placa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EntradaIdIngresoV = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 50, 50));

        EtiquetaNotas.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        EtiquetaNotas.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaNotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaNotas.setText("Edicion de Nota");
        getContentPane().add(EtiquetaNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 560, 47));

        EntradaManoDeObra.setColumns(20);
        EntradaManoDeObra.setRows(5);
        jScrollPane1.setViewportView(EntradaManoDeObra);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 560, 100));

        EntradaRefaccionesT.setColumns(20);
        EntradaRefaccionesT.setRows(5);
        jScrollPane2.setViewportView(EntradaRefaccionesT);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 560, 110));

        EntradaManoDeObraD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaManoDeObraDKeyTyped(evt);
            }
        });
        getContentPane().add(EntradaManoDeObraD, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 100, 30));

        EntradaCostoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaCostoRActionPerformed(evt);
            }
        });
        EntradaCostoR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaCostoRKeyTyped(evt);
            }
        });
        getContentPane().add(EntradaCostoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, 100, 30));

        EdicionNota.setText("EditarNota");
        EdicionNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdicionNotaActionPerformed(evt);
            }
        });
        getContentPane().add(EdicionNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mano De obra:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 90, 34));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Refacciones:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 75, 35));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Costo de mano de obra:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 140, 40));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Costo de refacciones:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, -1, 43));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nombre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 75, 23));

        EntradaNombre.setEnabled(false);
        getContentPane().add(EntradaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 90, 30));

        EntradaIdCliente.setEnabled(false);
        EntradaIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaIdClienteActionPerformed(evt);
            }
        });
        EntradaIdCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaIdClienteKeyTyped(evt);
            }
        });
        getContentPane().add(EntradaIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 90, 30));

        EntradaApellidoP.setEnabled(false);
        getContentPane().add(EntradaApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 130, 30));

        EntradaIdVehiculo.setEnabled(false);
        EntradaIdVehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaIdVehiculoKeyTyped(evt);
            }
        });
        getContentPane().add(EntradaIdVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 78, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Apellido Paterno");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, 23));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Apellido Materno");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, 23));

        EntradaApellidoM.setEnabled(false);
        getContentPane().add(EntradaApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 120, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Vehiculo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 70, 20));

        EntradaVehiculo.setEnabled(false);
        getContentPane().add(EntradaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 70, 30));

        Placa.setEnabled(false);
        Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaActionPerformed(evt);
            }
        });
        Placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PlacaKeyTyped(evt);
            }
        });
        getContentPane().add(Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 80, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Placa");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 80, 20));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Id Cliente");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 60, 20));

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Id Vehiculo");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 70, 20));

        EntradaIdIngresoV.setEnabled(false);
        EntradaIdIngresoV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaIdIngresoVKeyTyped(evt);
            }
        });
        getContentPane().add(EntradaIdIngresoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 90, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Numero Ingreso");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 100, 20));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        Back.setBorder(null);
        Back.setBorderPainted(false);
        Back.setContentAreaFilled(false);
        Back.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        Back.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso (1).png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 560, 60));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 560, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo5.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void RellenoDtos(String id){
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        String sql="select notas.IdNotas,notas.NumeroCliente,cliente.Nombre,cliente.ApellidoP,cliente.ApellidoM,notas.NumeroVehiculo,vehiculos.vehiculo,vehiculos.Placa,notas.NumeroIngresoVehiculo,notas.ManoDeObra,notas.CostoManoDeObra,notas.Refacciones,notas.CostoRefacciones from notas INNER JOIN cliente ON notas.NumeroCliente=cliente.IdCliente INNER JOIN vehiculos ON notas.NumeroVehiculo=vehiculos.IdVehiculos WHERE notas.IdNotas="+"'"+id+"'";
        String[] Dato=new String[13]; 
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                //Se guarda en el arreglo y del otro lado es la columna del valor
                Dato[0]=con.resultado.getString(1);
                Dato[1]=con.resultado.getString(2);
                Dato[2]=con.resultado.getString(3);
                Dato[3]=con.resultado.getString(4);
                Dato[4]=con.resultado.getString(5);
                Dato[5]=con.resultado.getString(6);
                Dato[6]=con.resultado.getString(7);
                Dato[7]=con.resultado.getString(8);
                Dato[8]=con.resultado.getString(9);
                Dato[9]=con.resultado.getString(10);
                Dato[10]=con.resultado.getString(11);
                Dato[11]=con.resultado.getString(12);
                Dato[12]=con.resultado.getString(13); 
            }
            EntradaIdCliente.setText(Dato[1]);
            EntradaNombre.setText(Dato[2]);
            EntradaApellidoP.setText(Dato[3]);
            EntradaApellidoM.setText(Dato[4]);
            EntradaIdVehiculo.setText(Dato[5]);
            Placa.setText(Dato[7]);
            EntradaVehiculo.setText(Dato[6]);
            EntradaIdIngresoV.setText(Dato[8]);
            EntradaManoDeObra.setText(Dato[9]);
            EntradaManoDeObraD.setText(Dato[10]);
            EntradaRefaccionesT.setText(Dato[11]);
            EntradaCostoR.setText(Dato[12]);            
        } catch (SQLException ex) {
            Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
    private void EntradaCostoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaCostoRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaCostoRActionPerformed

    private void EdicionNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdicionNotaActionPerformed
        // TODO add your handling code here:
        int idNota=Integer.parseInt(ID.getText());
        String mano =EntradaManoDeObraD.getText();
        float MANO = Float.parseFloat(mano);
        String refa =EntradaCostoR.getText();
        float REFAC = Float.parseFloat(refa);
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        con.UpdateNota(idNota,EntradaManoDeObra.getText(),MANO,EntradaRefaccionesT.getText(),REFAC);
        Menu M= new Menu();
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EdicionNotaActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_BackActionPerformed

    
    private void EntradaIdClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaIdClienteKeyTyped
        // TODO add your handling code here:
    char car = evt.getKeyChar();
    if(Character.isDigit(car)){
    }else{
    evt.consume();
    getToolkit().beep();
    }
    }//GEN-LAST:event_EntradaIdClienteKeyTyped

    private void EntradaIdVehiculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaIdVehiculoKeyTyped
        // TODO add your handling code here:
                char car = evt.getKeyChar();
    if(Character.isDigit(car)){
    }else{
    evt.consume();
    getToolkit().beep();
    }
    }//GEN-LAST:event_EntradaIdVehiculoKeyTyped

    private void EntradaIdIngresoVKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaIdIngresoVKeyTyped
        // TODO add your handling code here:
                char car = evt.getKeyChar();
    if(Character.isDigit(car)){
    }else{
    evt.consume();
    getToolkit().beep();
    }
    }//GEN-LAST:event_EntradaIdIngresoVKeyTyped

    private void EntradaManoDeObraDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaManoDeObraDKeyTyped
        // TODO add your handling code here:
    char car = evt.getKeyChar();
    if(Character.isDigit(car)){
    }else{
    evt.consume();
    }
    }//GEN-LAST:event_EntradaManoDeObraDKeyTyped

    private void EntradaCostoRKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaCostoRKeyTyped
        // TODO add your handling code here:
                char car = evt.getKeyChar();
    if(Character.isDigit(car)){
    }else{
    evt.consume();
    }
    }//GEN-LAST:event_EntradaCostoRKeyTyped

    private void EntradaIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaIdClienteActionPerformed

    private void PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlacaActionPerformed

    private void PlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlacaKeyTyped
        // TODO add your handling code here:
     char car = evt.getKeyChar();
    if(Character.isDigit(car)){
    }else{
    evt.consume();
    }
    }//GEN-LAST:event_PlacaKeyTyped
 
 
 
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaEdicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaEdicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaEdicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaEdicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String Id = null;
                new NotaEdicion(Id).setVisible(true);
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton EdicionNota;
    private javax.swing.JTextField EntradaApellidoM;
    private javax.swing.JTextField EntradaApellidoP;
    private javax.swing.JTextField EntradaCostoR;
    private javax.swing.JTextField EntradaIdCliente;
    private javax.swing.JTextField EntradaIdIngresoV;
    private javax.swing.JTextField EntradaIdVehiculo;
    private javax.swing.JTextArea EntradaManoDeObra;
    private javax.swing.JTextField EntradaManoDeObraD;
    private javax.swing.JTextField EntradaNombre;
    private javax.swing.JTextArea EntradaRefaccionesT;
    private javax.swing.JTextField EntradaVehiculo;
    private javax.swing.JLabel EtiquetaNotas;
    private javax.swing.JLabel ID;
    private javax.swing.JTextField Placa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
