/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leuraojedamecanicos;
import ConexionBD.ConexionDiagnostico;
import ConexionBD.ConexionMySQL;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import mecanicos.SoloMayusculas;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Chiiv
 */
public class RegistroDiagnosticos extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaDiagnostico
     */
    public RegistroDiagnosticos() {
        initComponents();
        Mostrar("");
        this.setLocationRelativeTo(null);
        EntradaPlaca.setDocument(new SoloMayusculas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        public void Mostrar(String Placa)
    {
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
       DefaultTableModel model=new DefaultTableModel();
        model.addColumn("ID Diagnostico");
        model.addColumn("NumeroCliente");
        model.addColumn("Nombre");
        model.addColumn("Apellido P");
        model.addColumn("Apellido M");
        model.addColumn("Id vehiculo");
        model.addColumn("Vehiculo");
        model.addColumn("Serie");
        model.addColumn("Placa");
        model.addColumn("IdEstado");
        model.addColumn("Fecha Diagnostico");
        
        Tabla.setModel(model);
        String sql="";
        if(Placa.equals(""))
        {
           sql="select Diagnostico.IdDiagnostico,Diagnostico.NumeroCliente,Cliente.Nombre,Cliente.ApellidoP,Cliente.ApellidoM,Diagnostico.NumeroVehiculo,Vehiculos.Vehiculo,Vehiculos.Serie,Vehiculos.Placa,Diagnostico.IdEstadoCarro,Diagnostico.FechaDiagnostico from Diagnostico,Cliente,Vehiculos where Diagnostico.NumeroCliente=Cliente.IdCliente and Diagnostico.NumeroVehiculo = vehiculos.IdVehiculos order by diagnostico.FechaDiagnostico desc;"; 
        }else{
 
            sql="select Diagnostico.IdDiagnostico,Diagnostico.NumeroCliente,Cliente.Nombre,Cliente.ApellidoP,Cliente.ApellidoM,Diagnostico.NumeroVehiculo,Vehiculos.Vehiculo,Vehiculos.Serie,Vehiculos.Placa,Diagnostico.IdEstadoCarro,Diagnostico.FechaDiagnostico from Diagnostico,Cliente,Vehiculos where Diagnostico.NumeroCliente=Cliente.IdCliente and Diagnostico.NumeroVehiculo = vehiculos.IdVehiculos and vehiculos.Placa like '%"+Placa+"%' order by diagnostico.FechaDiagnostico desc;";    
        }
        
        String Datos[]=new String[12];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                Datos[0]=con.resultado.getString(1);
                Datos[1]=con.resultado.getString(2);
                Datos[2]=con.resultado.getString(3);
                Datos[3]=con.resultado.getString(4);
                Datos[4]=con.resultado.getString(5);
                Datos[5]=con.resultado.getString(6);
                Datos[6]=con.resultado.getString(7);
                Datos[7]=con.resultado.getString(8);
                Datos[8]=con.resultado.getString(9);
                Datos[9]=con.resultado.getString(10);
                Datos[10]=con.resultado.getString(11);
                
                
                model.addRow(Datos);
            }
            Tabla.setModel(model);
        } catch (SQLException ex) {
            //Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        EXIT = new javax.swing.JButton();
        EntradaPlaca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        BotonModifi = new javax.swing.JButton();
        BotonEliminarRegistro = new javax.swing.JButton();
        BotonImprimirDiag = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        EntradaIdIngresoV = new javax.swing.JTextField();
        EntradaIdDiagnostico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1050, 290));

        EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        EXIT.setBorder(null);
        EXIT.setBorderPainted(false);
        EXIT.setContentAreaFilled(false);
        EXIT.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        EXIT.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida (1).png"))); // NOI18N
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 90, 70));
        getContentPane().add(EntradaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, 30));

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registro de Diagnosticos Ingresados ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 370, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Placa:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jButton5.setText("Previzualizar Diagnostico");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 210, 50));

        BotonModifi.setText("Modificar Datos");
        BotonModifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModifiActionPerformed(evt);
            }
        });
        getContentPane().add(BotonModifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 220, 50));

        BotonEliminarRegistro.setText("Eliminar Diagnostico");
        BotonEliminarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEliminarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, 180, 50));

        BotonImprimirDiag.setText("Imprimir Diagnostico");
        BotonImprimirDiag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonImprimirDiagActionPerformed(evt);
            }
        });
        getContentPane().add(BotonImprimirDiag, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 190, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo5.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 540));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 100, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 110, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 110, 30));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 400, 110, 30));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 400, 100, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 110, 30));
        getContentPane().add(EntradaIdIngresoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 110, 30));
        getContentPane().add(EntradaIdDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Mostrar(EntradaPlaca.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      this.setVisible(false);
        Menu menu=new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int i=Tabla.getSelectedRow();
        TableModel model=Tabla.getModel();
        EntradaIdDiagnostico.setText(model.getValueAt(i,0).toString());
        EntradaIdIngresoV.setText(model.getValueAt(i,1).toString());
        jTextField2.setText(model.getValueAt(i,2).toString());
        jTextField3.setText(model.getValueAt(i,3).toString());
        jTextField4.setText(model.getValueAt(i,4).toString());
        jTextField5.setText(model.getValueAt(i,5).toString());
        jTextField6.setText(model.getValueAt(i,6).toString());
        jTextField7.setText(model.getValueAt(i,9).toString());
        
        /*
        int i= jTAlumnos.getSelectedRow();
        TableModel model= jTAlumnos.getModel();
        jtxtIdAlumno.setText(model.getValueAt(i,0).toString());
        jtxtNombre.setText(model.getValueAt(i,1).toString());
        jtxtApellidoP.setText(model.getValueAt(i,2).toString());
        jtxtApellidoM.setText(model.getValueAt(i,3).toString());
        */
        
    }//GEN-LAST:event_TablaMouseClicked

    private void BotonModifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModifiActionPerformed
        // TODO add your handling code here:
        ModificarDiagnostico modi=new ModificarDiagnostico(EntradaIdDiagnostico.getText());
        modi.setVisible(true);
        System.out.println("El id que se lleva sera:"+llevarId());
        this.dispose();
        
    }//GEN-LAST:event_BotonModifiActionPerformed

    private void BotonEliminarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarRegistroActionPerformed
        // TODO add your handling code here:
        ConexionMySQL Con=new ConexionMySQL();
        Con.ConectarBasedeDatos();
        //Con.EliminarRegistroVehiculosIngresado(EntradaIdIngresoV.getText());
        Con.EliminarRegistroDiagnostico(EntradaIdDiagnostico.getText());
        Mostrar("");
        try {
            Con.CerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(RegistroDiagnosticos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BotonEliminarRegistroActionPerformed

    private void BotonImprimirDiagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonImprimirDiagActionPerformed
        // TODO add your handling code here:
        String Id=EntradaIdDiagnostico.getText();
        System.out.println("Se llevara este dato a la busqueda:"+Id);
        ConexionDiagnostico diag=new ConexionDiagnostico();
        try {
            diag.JasperDiagnostico(Id);
            
        } catch (JRException | SQLException ex) {
            Logger.getLogger(RegistroDiagnosticos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonImprimirDiagActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        ModificarDiagnostico MD=new ModificarDiagnostico(EntradaIdDiagnostico.getText());
        MD.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "WARNING",JOptionPane.WARNING_MESSAGE,
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        // Instrucciones si verdadero
        System.exit(0);
        } else {
            // Instrucciones si falso

        }
    }//GEN-LAST:event_EXITActionPerformed
    
    public String llevarId()
    {
        String id=EntradaIdDiagnostico.getText();
        return id;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDiagnosticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDiagnosticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDiagnosticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDiagnosticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDiagnosticos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEliminarRegistro;
    private javax.swing.JButton BotonImprimirDiag;
    private javax.swing.JButton BotonModifi;
    private javax.swing.JButton EXIT;
    private javax.swing.JTextField EntradaIdDiagnostico;
    private javax.swing.JTextField EntradaIdIngresoV;
    private javax.swing.JTextField EntradaPlaca;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
