/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leuraojedamecanicos;


import ConexionBD.ConexionMySQL;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.*;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import mecanicos.SoloMayusculas;

/**
 *
 * @author Gerardo
 */
public class RegistrarCliente extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarCliente
     */
    public RegistrarCliente() {
        initComponents();
        Mostrar("");
        String nt=ObtenerNumeroRegistroCliente();
        int id=Integer.parseInt(nt);
        int ID=id+1;
        EtiquetaNID.setText(""+ID);
        this.setLocationRelativeTo(null);
        EntradaNombre.setDocument(new SoloMayusculas());
        EntradaApellidoP.setDocument(new SoloMayusculas());
        EntradaApellidoM.setDocument(new SoloMayusculas());
        Registrar.setVisible(false);
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        Tabla.enable(false);
        Mostrar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void Mostrar(String ID)
    {
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
       DefaultTableModel model=new DefaultTableModel();
        model.addColumn("Id Cliente");
        model.addColumn("Nombre");
        model.addColumn("Apellido Paterno");
        model.addColumn("Apellido Materno");
        model.addColumn("Direccion");
        model.addColumn("Telefono");
        Tabla.setModel(model);
        String sql="select * from cliente;";
        String Usuarios[]=new String[6];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                Usuarios[0]=con.resultado.getString(1);
                Usuarios[1]=con.resultado.getString(2);
                Usuarios[2]=con.resultado.getString(3);
                Usuarios[3]=con.resultado.getString(4);
                Usuarios[4]=con.resultado.getString(5);
                Usuarios[5]=con.resultado.getString(6);
                model.addRow(Usuarios);
            }
            Tabla.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    public String ObtenerNumeroRegistroCliente()
    {
        String id = null;
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        PreparedStatement ps;
        try {
            ps=con.conexion.prepareStatement("select IdCliente from cliente order by IdCliente desc");
            con.resultado=ps.executeQuery();
            if(con.resultado.next())
            {
            id=con.resultado.getString("IdCliente");
            System.out.println(id);
            }else
            {
                id="0";
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EntradaNombre = new javax.swing.JTextField();
        Registrar = new javax.swing.JButton();
        EntradaApellidoP = new javax.swing.JTextField();
        EntradaApellidoM = new javax.swing.JTextField();
        EntradaDireccion = new javax.swing.JTextField();
        EntradaTelefono = new javax.swing.JTextField();
        Regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        EtiquetaNID = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 186, -1));

        EntradaNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EntradaNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaNombreKeyTyped(evt);
            }
        });
        getContentPane().add(EntradaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 230, 28));

        Registrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 87, 38));

        EntradaApellidoP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(EntradaApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 230, 30));

        EntradaApellidoM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(EntradaApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 230, 30));

        EntradaDireccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(EntradaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 230, 30));

        EntradaTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EntradaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaTelefonoActionPerformed(evt);
            }
        });
        EntradaTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(EntradaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 230, 30));

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        Regresar.setBorder(null);
        Regresar.setBorderPainted(false);
        Regresar.setContentAreaFilled(false);
        Regresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        Regresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso (1).png"))); // NOI18N
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 93, 60));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 60, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 120, 29));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Apellido Materno:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 130, 27));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Direccion:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 80, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Telefono:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 70, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("El id del cliente");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 100, 30));

        jButton6.setText("Modificar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, 40));

        EtiquetaNID.setEnabled(false);
        getContentPane().add(EtiquetaNID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 70, 30));

        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 470, 330));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 80, 70));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 890, 220));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo5.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 700));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 440, 330));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        // TODO add your handling code here:
         ConexionMySQL Con=new ConexionMySQL();
        if(EntradaNombre.getText().isEmpty()||EntradaApellidoP.getText().isEmpty()||EntradaApellidoM.getText().isEmpty()||EntradaDireccion.getText().isEmpty()||EntradaTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Procure no dejar espacios vacios", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
        try{
            String u= EntradaApellidoP.getText();
            String c= EntradaApellidoM.getText();
            Con.ConectarBasedeDatos();
            String SQL="SELECT COUNT(IdCliente) AS i FROM cliente WHERE ApellidoP='"+u+"'"+" AND ApellidoM= '"+c+"'";
            Con.resultado=Con.sentencia.executeQuery(SQL);
            while (Con.resultado.next()){
                if (Con.resultado.getString("i").equals("1")){
                    JOptionPane.showMessageDialog(null, "El cliente: "+EntradaNombre.getText()+" "+EntradaApellidoP.getText()+" "+ EntradaApellidoM.getText()+ " ya se encuentra Registrado", "Error al registrar", 0);
                    EntradaNombre.setText("");
                    EntradaApellidoP.setText("");
                    EntradaApellidoM.setText("");
                    EntradaDireccion.setText("");
                    EntradaTelefono.setText("");
                }else{
        Con.ConectarBasedeDatos();
        Con.GuardarCliente(EntradaNombre.getText(), EntradaApellidoP.getText(), EntradaApellidoM.getText(), EntradaDireccion.getText(), EntradaTelefono.getText());
                    if (JOptionPane.showConfirmDialog(null, "¿Desea Registrar un Vehiculo?", "NOTIFICACION",JOptionPane.WARNING_MESSAGE,JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                        RegistrarVehiculo RV=new RegistrarVehiculo();
                        RV.setVisible(true);
                        //AQUI MODIFICAR
                        
                        RV.jButton1.setVisible(true);
                        RV.Tabla.enable(true);
            this.dispose();
                    }else{
                    EntradaNombre.setText("");
                    EntradaApellidoP.setText("");
                    EntradaApellidoM.setText("");
                    EntradaDireccion.setText("");
                    EntradaTelefono.setText("");
                            String nt=ObtenerNumeroRegistroCliente();
                            int id=Integer.parseInt(nt);
                            int ID=id+1;
                            EtiquetaNID.setText(""+ID);
                            Mostrar("");
                    }
                }
            }
            Con.DesconectarBasedeDatos();
        } catch (SQLException ex){
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE,null,ex);
        }
        }
    }//GEN-LAST:event_RegistrarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuRegistros menu=new MenuRegistros();
        menu.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "WARNING",JOptionPane.WARNING_MESSAGE,
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        // Instrucciones si verdadero
        System.exit(0);
        } else {
            // Instrucciones si falso

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EntradaTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaTelefonoKeyTyped
        // TODO add your handling code here:
    if(EntradaTelefono.getText().length()>=10){
        evt.consume();
        getToolkit().beep();
    }else{
        char car = evt.getKeyChar();
    if(Character.isDigit(car)){
    }else{
    evt.consume();
    }
    }
    }//GEN-LAST:event_EntradaTelefonoKeyTyped

    private void EntradaNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaNombreKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        if(EtiquetaNID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No dejes el campo vacio. Introduce un valor...", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        String sql="select Nombre, ApellidoP, ApellidoM, Direccion, Telefono from cliente where IdCliente="+"'"+EtiquetaNID.getText()+"'";
        String Usuarios[]=new String[5];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                //Se guarda en el arreglo y del otro lado es la columna del valor
                Usuarios[0]=con.resultado.getString(1);
                Usuarios[1]=con.resultado.getString(2);
                Usuarios[2]=con.resultado.getString(3);
                Usuarios[3]=con.resultado.getString(4);
                Usuarios[4]=con.resultado.getString(5);
            }
            EntradaNombre.setText(Usuarios[0]);
            EntradaApellidoP.setText(Usuarios[1]);
            EntradaApellidoM.setText(Usuarios[2]);
            EntradaDireccion.setText(Usuarios[3]);
            EntradaTelefono.setText(Usuarios[4]);
        } catch (SQLException ex) {
            Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int i=Tabla.getSelectedRow();
        TableModel model=Tabla.getModel();
        EtiquetaNID.setText(model.getValueAt(i,0).toString());
        EntradaNombre.setText(model.getValueAt(i,1).toString());
        EntradaApellidoP.setText(model.getValueAt(i,2).toString());
        EntradaApellidoM.setText(model.getValueAt(i,3).toString());
        EntradaDireccion.setText(model.getValueAt(i,4).toString());
        EntradaTelefono.setText(model.getValueAt(i,5).toString());   
    }//GEN-LAST:event_TablaMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(EtiquetaNID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Primero realiza la busqueda con el Id del Vehiculo o selecciona desde la tabla", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
        if(EntradaNombre.getText().isEmpty()||EntradaApellidoP.getText().isEmpty()||EntradaApellidoM.getText().isEmpty()||EntradaDireccion.getText().isEmpty()||EntradaTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Procure no dejar espacios vacios", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{ConexionMySQL Con=new ConexionMySQL();
         Con.ConectarBasedeDatos();
        String nte=EtiquetaNID.getText();
        int idc=Integer.parseInt(nte);
        Con.UpdateCliente(EntradaNombre.getText(),EntradaApellidoP.getText(),EntradaApellidoM.getText(),EntradaDireccion.getText(),EntradaTelefono.getText(),idc);
        EtiquetaNID.setText("");
        EntradaNombre.setText("");
        EntradaApellidoP.setText("");
        EntradaApellidoM.setText("");
        EntradaDireccion.setText("");
        EntradaTelefono.setText("");
        }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void EntradaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaTelefonoActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EntradaApellidoM;
    private javax.swing.JTextField EntradaApellidoP;
    private javax.swing.JTextField EntradaDireccion;
    private javax.swing.JTextField EntradaNombre;
    private javax.swing.JTextField EntradaTelefono;
    public javax.swing.JTextField EtiquetaNID;
    public javax.swing.JButton Registrar;
    private javax.swing.JButton Regresar;
    public javax.swing.JTable Tabla;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
