/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leuraojedamecanicos;

import ConexionBD.ConexionMySQL;
import leuraojedamecanicos.*;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.*;
import java.util.logging.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import mecanicos.SoloMayusculas;

/**
 *
 * @author Gerardo
 */
public class RegistrarVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarCliente
     */
    public RegistrarVehiculo() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LogoH.png")));
        this.setLocationRelativeTo(null);
        jButton1.setVisible(false);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jLabel30.setVisible(false);
        EntradaIdVehiculo.setVisible(false);
        EntradaVehiculo.setDocument(new SoloMayusculas());
        EntradaSerie.setDocument(new SoloMayusculas());
        EntradaPlaca.setDocument(new SoloMayusculas());
        Tabla.enable(false);
        Mostrar("");
    }

    public void Mostrar(String ID)
    {
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
       DefaultTableModel model=new DefaultTableModel();
        model.addColumn("Id Vehiculo");
        model.addColumn("Id Cliente");
        model.addColumn("Vehiculo");
        model.addColumn("Serie");
        model.addColumn("Placa");
        Tabla.setModel(model);
        String sql="select * from vehiculos;";
        String Usuarios[]=new String[5];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                Usuarios[0]=con.resultado.getString(1);
                Usuarios[1]=con.resultado.getString(2);
                Usuarios[2]=con.resultado.getString(3);
                Usuarios[3]=con.resultado.getString(4);
                Usuarios[4]=con.resultado.getString(5);
                model.addRow(Usuarios);
            }
            Tabla.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        EtiquetaSerie = new javax.swing.JLabel();
        EtiquetaPlaca = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        EtiquetaVehiculo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EntradaSerie = new javax.swing.JTextField();
        EntradaPlaca = new javax.swing.JTextField();
        EntradaIdVehiculo = new javax.swing.JTextField();
        EntradaVehiculo = new javax.swing.JTextField();
        EntradaIdCliente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel12.setText("Vehiculo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        EtiquetaSerie.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EtiquetaSerie.setText("Serie:");
        getContentPane().add(EtiquetaSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 40, 20));

        EtiquetaPlaca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EtiquetaPlaca.setText("Placa:");
        getContentPane().add(EtiquetaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 50, 20));

        jLabel30.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel30.setText("Id Vehículo:");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 80, 40));

        EtiquetaVehiculo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EtiquetaVehiculo.setText("Vehículo:");
        getContentPane().add(EtiquetaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 60, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Id Cliente:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 80, 20));
        getContentPane().add(EntradaSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 250, 30));
        getContentPane().add(EntradaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 250, 30));

        EntradaIdVehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaIdVehiculoKeyTyped(evt);
            }
        });
        getContentPane().add(EntradaIdVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 80, 30));
        getContentPane().add(EntradaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 250, 30));

        EntradaIdCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EntradaIdClienteKeyTyped(evt);
            }
        });
        getContentPane().add(EntradaIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 250, 30));

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, 40));

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        Regresar.setBorder(null);
        Regresar.setBorderPainted(false);
        Regresar.setContentAreaFilled(false);
        Regresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        Regresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso (1).png"))); // NOI18N
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 93, 60));

        jButton7.setText("Modificar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, 40));

        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 400, 380));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 460, 700, 160));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 80, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo5.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 650));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 440, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MenuRegistros menu=new MenuRegistros();
        menu.setVisible(true);
    }//GEN-LAST:event_RegresarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "WARNING",JOptionPane.WARNING_MESSAGE,
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        // Instrucciones si verdadero
        System.exit(0);
        } else {
            // Instrucciones si falso

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         ConexionMySQL Con=new ConexionMySQL();
        if(EntradaIdCliente.getText().isEmpty()||EntradaVehiculo.getText().isEmpty()||EntradaSerie.getText().isEmpty()||EntradaPlaca.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Procure no dejar espacios vacios", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
        try{
            String u= EntradaIdCliente.getText();
            String c= EntradaPlaca.getText();
            Con.ConectarBasedeDatos();
            String SQL="SELECT COUNT(IdVehiculos) AS i FROM Vehiculos WHERE IdClienteV='"+u+"'"+" AND Placa= '"+c+"'";
            Con.resultado=Con.sentencia.executeQuery(SQL);
            while (Con.resultado.next()){
                if (Con.resultado.getString("i").equals("1")){
                    JOptionPane.showMessageDialog(null, "El Vehiculo ya se encuentra Registrado", "Error al registrar", 0);
                    EntradaIdCliente.setText("");
                    EntradaVehiculo.setText("");
                    EntradaSerie.setText("");
                    EntradaPlaca.setText("");
                }else{
        String ntec=EntradaIdCliente.getText();
        int idec=Integer.parseInt(ntec);
        Con.ConectarBasedeDatos();
        Con.GuardarVehiculo(idec, EntradaVehiculo.getText(), EntradaSerie.getText(), EntradaPlaca.getText());
        EntradaIdCliente.setText("");
        EntradaVehiculo.setText("");
        EntradaSerie.setText("");
        EntradaPlaca.setText("");
        Mostrar("");

                }
            }
            Con.DesconectarBasedeDatos();
        } catch (SQLException ex){
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE,null,ex);
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EntradaIdVehiculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaIdVehiculoKeyTyped
        // TODO add your handling code here:
    if(EntradaIdVehiculo.getText().length()>=3){
        evt.consume();
        getToolkit().beep();
    }else{
        char car = evt.getKeyChar();
    if(Character.isDigit(car)){
    }else{
    evt.consume();
    }
    }
    }//GEN-LAST:event_EntradaIdVehiculoKeyTyped

    private void EntradaIdClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EntradaIdClienteKeyTyped
        // TODO add your handling code here:
    if(EntradaIdCliente.getText().length()>=3){
        evt.consume();
        getToolkit().beep();
    }else{
        char car = evt.getKeyChar();
    if(Character.isDigit(car)){
    }else{
    evt.consume();
    }
    }
    }//GEN-LAST:event_EntradaIdClienteKeyTyped

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(EntradaIdVehiculo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Primero realiza la busqueda con el Id del Vehiculo", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
        if(EntradaIdCliente.getText().isEmpty()||EntradaVehiculo.getText().isEmpty()||EntradaSerie.getText().isEmpty()||EntradaPlaca.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Procure no dejar espacios vacios", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{ConexionMySQL Con=new ConexionMySQL();
         Con.ConectarBasedeDatos();
        String nte=EntradaIdCliente.getText();
        int idc=Integer.parseInt(nte);
        String ntv=EntradaIdVehiculo.getText();
        int idv=Integer.parseInt(ntv);
         Con.UpdateVehiculo(idc,EntradaVehiculo.getText(), EntradaSerie.getText(), EntradaPlaca.getText(), idv);
        EntradaIdVehiculo.setText("");
        EntradaIdCliente.setText("");
        EntradaVehiculo.setText("");
        EntradaSerie.setText("");
        EntradaPlaca.setText("");
        }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
        if(EntradaIdVehiculo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No dejes el campo vacio. Introduce un valor...", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else{
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
        String sql="select idClienteV,Vehiculo,Serie,Placa from vehiculos where idVehiculos="+"'"+EntradaIdVehiculo.getText()+"'";
        String Usuarios[]=new String[4];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                //Se guarda en el arreglo y del otro lado es la columna del valor
                Usuarios[0]=con.resultado.getString(1);
                Usuarios[1]=con.resultado.getString(2);
                Usuarios[2]=con.resultado.getString(3);
                Usuarios[3]=con.resultado.getString(4);
            }
            EntradaIdCliente.setText(Usuarios[0]);
            EntradaVehiculo.setText(Usuarios[1]);
            EntradaSerie.setText(Usuarios[2]);
            EntradaPlaca.setText(Usuarios[3]);
            
        } catch (SQLException ex) {
            Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
       }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int i=Tabla.getSelectedRow();
        TableModel model=Tabla.getModel();
        EntradaIdVehiculo.setText(model.getValueAt(i,0).toString());
        EntradaIdCliente.setText(model.getValueAt(i,1).toString());
        EntradaVehiculo.setText(model.getValueAt(i,2).toString());
        EntradaSerie.setText(model.getValueAt(i,3).toString());
        EntradaPlaca.setText(model.getValueAt(i,4).toString());
    }//GEN-LAST:event_TablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EntradaIdCliente;
    public javax.swing.JTextField EntradaIdVehiculo;
    private javax.swing.JTextField EntradaPlaca;
    private javax.swing.JTextField EntradaSerie;
    private javax.swing.JTextField EntradaVehiculo;
    private javax.swing.JLabel EtiquetaPlaca;
    private javax.swing.JLabel EtiquetaSerie;
    private javax.swing.JLabel EtiquetaVehiculo;
    private javax.swing.JButton Regresar;
    public javax.swing.JTable Tabla;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
