/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package leuraojedamecanicos;

import ConexionBD.ConexionMySQL;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import mecanicos.SoloMayusculas;

/**
 *
 * @author Chiiv
 */
public class RegistroDeVehiculosIngresados extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaDiagnostico
     */
    public RegistroDeVehiculosIngresados() {
        initComponents();
        Mostrar("","");
        this.setLocationRelativeTo(null);
        EntradaVehiculo.setDocument(new SoloMayusculas());
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/LogoH.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        public void Mostrar(String Placa,String Vehiculo)
    {
        ConexionMySQL con=new ConexionMySQL();
        con.ConectarBasedeDatos();
       DefaultTableModel model=new DefaultTableModel();
        model.addColumn("ID Diagnostico");
        model.addColumn("ID del ingreso del vehiculo");
        model.addColumn("Numero de Cliente");
        model.addColumn("Nombre");
        model.addColumn("Numero de vehiculo");
        model.addColumn("Vehiculo");
        model.addColumn("Placa");
        model.addColumn("Fecha De Ingreso");
         
        Tabla.setModel(model);
        String sql="";
        if(Placa.equals("") && Vehiculo.equals(""))
        {
           sql="SELECT Ingresarvehiculos.NumeroDiagnostico,Ingresarvehiculos.IdIngresoVehiculo,Ingresarvehiculos.NumeroCliente,Cliente.Nombre,Ingresarvehiculos.NumeroVehiculo,Vehiculos.Placa,Vehiculos.Vehiculo,Ingresarvehiculos.FechaIngreso FROM IngresarVehiculos,cliente,vehiculos where Ingresarvehiculos.NumeroCliente=Cliente.IdCliente and Ingresarvehiculos.NumeroVehiculo=Vehiculos.IdVehiculos;"; 
        }else{
            if(Vehiculo.equals(""))
            {
            sql="SELECT Ingresarvehiculos.NumeroDiagnostico,Ingresarvehiculos.IdIngresoVehiculo,Ingresarvehiculos.NumeroCliente,Cliente.Nombre,Ingresarvehiculos.NumeroVehiculo,Vehiculos.Placa,Vehiculos.Vehiculo,Ingresarvehiculos.FechaIngreso FROM IngresarVehiculos,cliente,vehiculos where Ingresarvehiculos.NumeroCliente=Cliente.IdCliente and Ingresarvehiculos.NumeroVehiculo=Vehiculos.IdVehiculos and vehiculos.Placa like '%"+Placa+"%' order by ingresarvehiculos.FechaIngreso desc;";
            }else
            {
            sql="SELECT Ingresarvehiculos.NumeroDiagnostico,Ingresarvehiculos.IdIngresoVehiculo,Ingresarvehiculos.NumeroCliente,Cliente.Nombre,Ingresarvehiculos.NumeroVehiculo,Vehiculos.Placa,Vehiculos.Vehiculo,Ingresarvehiculos.FechaIngreso FROM IngresarVehiculos,cliente,vehiculos where Ingresarvehiculos.NumeroCliente=Cliente.IdCliente and Ingresarvehiculos.NumeroVehiculo=Vehiculos.IdVehiculos and vehiculos.vehiculo like '%"+Vehiculo+"%' order by ingresarvehiculos.FechaIngreso desc;";    
            }
        }
        
        String Datos[]=new String[8];
        Statement set;
        try {
            set=con.conexion.createStatement();
            con.resultado=set.executeQuery(sql);
            while(con.resultado.next())
            {
                Datos[0]=con.resultado.getString(1);
                Datos[1]=con.resultado.getString(2);
                Datos[2]=con.resultado.getString(3);
                Datos[3]=con.resultado.getString(4);
                Datos[4]=con.resultado.getString(5);
                Datos[5]=con.resultado.getString(6);
                Datos[6]=con.resultado.getString(7);
                Datos[7]=con.resultado.getString(8);
              
                model.addRow(Datos);
            }
            Tabla.setModel(model);
        } catch (SQLException ex) {
            //Logger.getLogger(Registros.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        EXIT = new javax.swing.JButton();
        EntradaPlaca = new javax.swing.JTextField();
        EntradaVehiculo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        BotonEliminarRegistro = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        EntradaIdIngresoV = new javax.swing.JTextField();
        EntradaIdDiagnostico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1060, 230));

        EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        EXIT.setBorder(null);
        EXIT.setBorderPainted(false);
        EXIT.setContentAreaFilled(false);
        EXIT.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida.png"))); // NOI18N
        EXIT.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/salida (1).png"))); // NOI18N
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 90, 70));
        getContentPane().add(EntradaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, 30));
        getContentPane().add(EntradaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 130, 30));

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/regreso (1).png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vehiculo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registro de Vehiculos Ingresados ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 370, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Placa:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jButton3.setText("Modificar Datos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 150, 50));

        BotonEliminarRegistro.setText("Eliminar Ingreso Del Vehiculo");
        BotonEliminarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEliminarRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 220, 50));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 100, 30));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 110, 30));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 110, 30));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 400, 110, 30));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 400, 100, 30));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 110, 30));
        getContentPane().add(EntradaIdIngresoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 110, 30));
        getContentPane().add(EntradaIdDiagnostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 120, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo5.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Mostrar(EntradaPlaca.getText(),EntradaVehiculo.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      this.setVisible(false);
        Menu menu=new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        int i=Tabla.getSelectedRow();
        TableModel model=Tabla.getModel();
        EntradaIdDiagnostico.setText(model.getValueAt(i,0).toString());
        EntradaIdIngresoV.setText(model.getValueAt(i,1).toString());
        jTextField2.setText(model.getValueAt(i,2).toString());
        jTextField3.setText(model.getValueAt(i,3).toString());
        jTextField4.setText(model.getValueAt(i,4).toString());
        jTextField5.setText(model.getValueAt(i,5).toString());
        jTextField6.setText(model.getValueAt(i,6).toString());
        jTextField7.setText(model.getValueAt(i,7).toString());
        
        /*
        int i= jTAlumnos.getSelectedRow();
        TableModel model= jTAlumnos.getModel();
        jtxtIdAlumno.setText(model.getValueAt(i,0).toString());
        jtxtNombre.setText(model.getValueAt(i,1).toString());
        jtxtApellidoP.setText(model.getValueAt(i,2).toString());
        jtxtApellidoM.setText(model.getValueAt(i,3).toString());
        */
        
    }//GEN-LAST:event_TablaMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ModificarIngresoVehiculo modi=new ModificarIngresoVehiculo(EntradaIdIngresoV.getText());
        modi.setVisible(true);
        System.out.println("El id que se lleva sera:"+llevarId());
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BotonEliminarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarRegistroActionPerformed
        // TODO add your handling code here:
        ConexionMySQL Con=new ConexionMySQL();
        Con.ConectarBasedeDatos();
        Con.EliminarRegistroVehiculosIngresado(EntradaIdIngresoV.getText());
        //Con.EliminarRegistroDiagnostico(EntradaIdDiagnostico.getText());
        Mostrar("","");
        try {
            Con.CerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(RegistroDeVehiculosIngresados.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BotonEliminarRegistroActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?", "WARNING",JOptionPane.WARNING_MESSAGE,
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        // Instrucciones si verdadero
        System.exit(0);
        } else {
            // Instrucciones si falso

        }
    }//GEN-LAST:event_EXITActionPerformed
    
    public String llevarId()
    {
        String id=EntradaIdIngresoV.getText();
        return id;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroDeVehiculosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroDeVehiculosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroDeVehiculosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroDeVehiculosIngresados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroDeVehiculosIngresados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEliminarRegistro;
    private javax.swing.JButton EXIT;
    private javax.swing.JTextField EntradaIdDiagnostico;
    private javax.swing.JTextField EntradaIdIngresoV;
    private javax.swing.JTextField EntradaPlaca;
    private javax.swing.JTextField EntradaVehiculo;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
